// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/testapi/create-did": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a DID using method and public key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create DID",
                "operationId": "createDid",
                "parameters": [
                    {
                        "description": "Create DID request",
                        "name": "CreateDidRequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateDidRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" example({\"did\":\"did:byd50:1234567890abcdef\"})",
                        "schema": {
                            "$ref": "#/definitions/api.CreateDidResponse"
                        }
                    },
                    "400": {
                        "description": "bad request\" example({\"code\":\"INVALID_PARAM\",\"message\":\"method and public_key_base58 are required\"})",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal error\" example({\"code\":\"INTERNAL_ERROR\",\"message\":\"failed to create did\"})",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/testapi/get-did-public-key/{some_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Resolve a DID and return its public key (Base58).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Get DID Public Key",
                "operationId": "getDidPublicKey",
                "parameters": [
                    {
                        "type": "string",
                        "description": "DID",
                        "name": "some_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" example({\"publicKeyBase58\":\"3VZ6oJdR8i1qKX7kH3Yv9d7w7wzgn...\"})",
                        "schema": {
                            "$ref": "#/definitions/api.GetDidPublicKeyResponse"
                        }
                    },
                    "400": {
                        "description": "bad request\" example({\"code\":\"INVALID_PARAM\",\"message\":\"did is required\"})",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "not found\" example({\"code\":\"NOT_FOUND\",\"message\":\"public key not found\"})",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/testapi/get-did/{some_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Resolve a DID and return its DID Document.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Get DID Document",
                "operationId": "getDidDocument",
                "parameters": [
                    {
                        "type": "string",
                        "description": "DID",
                        "name": "some_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" example({\"document\":\"{...did document json...}\"})",
                        "schema": {
                            "$ref": "#/definitions/api.GetDidResponse"
                        }
                    },
                    "400": {
                        "description": "bad request\" example({\"code\":\"INVALID_PARAM\",\"message\":\"did is required\"})",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "not found\" example({\"code\":\"NOT_FOUND\",\"message\":\"did document not found\"})",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CreateDidRequestBody": {
            "type": "object",
            "properties": {
                "method": {
                    "type": "string",
                    "example": "byd50"
                },
                "public_key_base58": {
                    "type": "string",
                    "example": "3VZ6oJdR8i1qKX7kH3Yv9d7w7wzgn..."
                }
            }
        },
        "api.CreateDidResponse": {
            "type": "object",
            "properties": {
                "did": {
                    "type": "string",
                    "example": "did:byd50:1234567890abcdef"
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "INVALID_PARAM"
                },
                "message": {
                    "type": "string",
                    "example": "method and public_key_base58 are required"
                }
            }
        },
        "api.GetDidPublicKeyResponse": {
            "type": "object",
            "properties": {
                "publicKeyBase58": {
                    "type": "string",
                    "example": "3VZ6oJdR8i1qKX7kH3Yv9d7w7wzgn..."
                }
            }
        },
        "api.GetDidResponse": {
            "type": "object",
            "properties": {
                "document": {
                    "type": "string",
                    "example": "{\\\"@context\\\":[\\\"https://www.w3.org/ns/did/v1\\\"],\\\"id\\\":\\\"did:byd50:123\\\",\\\"verificationMethod\\\":[...]}"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v2",
	Schemes:          []string{},
	Title:            "DID Phase 2 Test API",
	Description:      "This is a sample server for DID ServiceEndpoint.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
