// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto-files/issuer.proto

package proto_files

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the vcClaimJwt.
type CredentialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VcClaimJwt string `protobuf:"bytes,1,opt,name=vcClaimJwt,proto3" json:"vcClaimJwt,omitempty"`
}

func (x *CredentialRequest) Reset() {
	*x = CredentialRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_issuer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialRequest) ProtoMessage() {}

func (x *CredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_issuer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialRequest.ProtoReflect.Descriptor instead.
func (*CredentialRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_issuer_proto_rawDescGZIP(), []int{0}
}

func (x *CredentialRequest) GetVcClaimJwt() string {
	if x != nil {
		return x.VcClaimJwt
	}
	return ""
}

// The response message containing the vcJwt
type CredentialReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VcJwt string `protobuf:"bytes,1,opt,name=vcJwt,proto3" json:"vcJwt,omitempty"`
}

func (x *CredentialReply) Reset() {
	*x = CredentialReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_issuer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredentialReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialReply) ProtoMessage() {}

func (x *CredentialReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_issuer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialReply.ProtoReflect.Descriptor instead.
func (*CredentialReply) Descriptor() ([]byte, []int) {
	return file_proto_files_issuer_proto_rawDescGZIP(), []int{1}
}

func (x *CredentialReply) GetVcJwt() string {
	if x != nil {
		return x.VcJwt
	}
	return ""
}

// The request message containing the did.
type IdCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (x *IdCardRequest) Reset() {
	*x = IdCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_issuer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdCardRequest) ProtoMessage() {}

func (x *IdCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_issuer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdCardRequest.ProtoReflect.Descriptor instead.
func (*IdCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_issuer_proto_rawDescGZIP(), []int{2}
}

func (x *IdCardRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

// The response message containing the eIdVcJwt
type IdCardReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EIdVcJwt string `protobuf:"bytes,1,opt,name=eIdVcJwt,proto3" json:"eIdVcJwt,omitempty"`
}

func (x *IdCardReply) Reset() {
	*x = IdCardReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_issuer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdCardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdCardReply) ProtoMessage() {}

func (x *IdCardReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_issuer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdCardReply.ProtoReflect.Descriptor instead.
func (*IdCardReply) Descriptor() ([]byte, []int) {
	return file_proto_files_issuer_proto_rawDescGZIP(), []int{3}
}

func (x *IdCardReply) GetEIdVcJwt() string {
	if x != nil {
		return x.EIdVcJwt
	}
	return ""
}

// The request message containing the eIdVcJwt.
type DlCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EIdVcJwt string `protobuf:"bytes,1,opt,name=eIdVcJwt,proto3" json:"eIdVcJwt,omitempty"`
}

func (x *DlCardRequest) Reset() {
	*x = DlCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_issuer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DlCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DlCardRequest) ProtoMessage() {}

func (x *DlCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_issuer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DlCardRequest.ProtoReflect.Descriptor instead.
func (*DlCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_issuer_proto_rawDescGZIP(), []int{4}
}

func (x *DlCardRequest) GetEIdVcJwt() string {
	if x != nil {
		return x.EIdVcJwt
	}
	return ""
}

// The response message containing the driver's license
type DlCardReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid    bool   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Result   string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	EDlVcJwt string `protobuf:"bytes,3,opt,name=eDlVcJwt,proto3" json:"eDlVcJwt,omitempty"`
}

func (x *DlCardReply) Reset() {
	*x = DlCardReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_issuer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DlCardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DlCardReply) ProtoMessage() {}

func (x *DlCardReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_issuer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DlCardReply.ProtoReflect.Descriptor instead.
func (*DlCardReply) Descriptor() ([]byte, []int) {
	return file_proto_files_issuer_proto_rawDescGZIP(), []int{5}
}

func (x *DlCardReply) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *DlCardReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *DlCardReply) GetEDlVcJwt() string {
	if x != nil {
		return x.EDlVcJwt
	}
	return ""
}

// The request message containing the driver's license.
type RentalCarAgreementRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EDlVcJwt string `protobuf:"bytes,1,opt,name=eDlVcJwt,proto3" json:"eDlVcJwt,omitempty"`
}

func (x *RentalCarAgreementRequest) Reset() {
	*x = RentalCarAgreementRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_issuer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RentalCarAgreementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RentalCarAgreementRequest) ProtoMessage() {}

func (x *RentalCarAgreementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_issuer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RentalCarAgreementRequest.ProtoReflect.Descriptor instead.
func (*RentalCarAgreementRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_issuer_proto_rawDescGZIP(), []int{6}
}

func (x *RentalCarAgreementRequest) GetEDlVcJwt() string {
	if x != nil {
		return x.EDlVcJwt
	}
	return ""
}

// The response message containing the rentalCarVcJwt
type RentalCarAgreementReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid                   bool   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Result                  string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	RentalCarAgreementVcJwt string `protobuf:"bytes,3,opt,name=rentalCarAgreementVcJwt,proto3" json:"rentalCarAgreementVcJwt,omitempty"`
}

func (x *RentalCarAgreementReply) Reset() {
	*x = RentalCarAgreementReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_issuer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RentalCarAgreementReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RentalCarAgreementReply) ProtoMessage() {}

func (x *RentalCarAgreementReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_issuer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RentalCarAgreementReply.ProtoReflect.Descriptor instead.
func (*RentalCarAgreementReply) Descriptor() ([]byte, []int) {
	return file_proto_files_issuer_proto_rawDescGZIP(), []int{7}
}

func (x *RentalCarAgreementReply) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *RentalCarAgreementReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *RentalCarAgreementReply) GetRentalCarAgreementVcJwt() string {
	if x != nil {
		return x.RentalCarAgreementVcJwt
	}
	return ""
}

// The request message containing the rentalCarVcJwt.
type RentalCarControlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RentalCarAgreementVcJwt string `protobuf:"bytes,1,opt,name=rentalCarAgreementVcJwt,proto3" json:"rentalCarAgreementVcJwt,omitempty"`
}

func (x *RentalCarControlRequest) Reset() {
	*x = RentalCarControlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_issuer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RentalCarControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RentalCarControlRequest) ProtoMessage() {}

func (x *RentalCarControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_issuer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RentalCarControlRequest.ProtoReflect.Descriptor instead.
func (*RentalCarControlRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_issuer_proto_rawDescGZIP(), []int{8}
}

func (x *RentalCarControlRequest) GetRentalCarAgreementVcJwt() string {
	if x != nil {
		return x.RentalCarAgreementVcJwt
	}
	return ""
}

// The response message containing the result
type RentalCarControlReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid  bool   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Result string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *RentalCarControlReply) Reset() {
	*x = RentalCarControlReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_issuer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RentalCarControlReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RentalCarControlReply) ProtoMessage() {}

func (x *RentalCarControlReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_issuer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RentalCarControlReply.ProtoReflect.Descriptor instead.
func (*RentalCarControlReply) Descriptor() ([]byte, []int) {
	return file_proto_files_issuer_proto_rawDescGZIP(), []int{9}
}

func (x *RentalCarControlReply) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *RentalCarControlReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_proto_files_issuer_proto protoreflect.FileDescriptor

var file_proto_files_issuer_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x69, 0x73,
	0x73, 0x75, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x69, 0x73, 0x73, 0x75,
	0x65, 0x72, 0x22, 0x33, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x63, 0x43, 0x6c, 0x61,
	0x69, 0x6d, 0x4a, 0x77, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x63, 0x43,
	0x6c, 0x61, 0x69, 0x6d, 0x4a, 0x77, 0x74, 0x22, 0x27, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x63,
	0x4a, 0x77, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x63, 0x4a, 0x77, 0x74,
	0x22, 0x21, 0x0a, 0x0d, 0x49, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x64, 0x69, 0x64, 0x22, 0x29, 0x0a, 0x0b, 0x49, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x49, 0x64, 0x56, 0x63, 0x4a, 0x77, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x49, 0x64, 0x56, 0x63, 0x4a, 0x77, 0x74, 0x22, 0x2b,
	0x0a, 0x0d, 0x44, 0x6c, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x65, 0x49, 0x64, 0x56, 0x63, 0x4a, 0x77, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x65, 0x49, 0x64, 0x56, 0x63, 0x4a, 0x77, 0x74, 0x22, 0x57, 0x0a, 0x0b, 0x44,
	0x6c, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x44, 0x6c, 0x56,
	0x63, 0x4a, 0x77, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x44, 0x6c, 0x56,
	0x63, 0x4a, 0x77, 0x74, 0x22, 0x37, 0x0a, 0x19, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x43, 0x61,
	0x72, 0x41, 0x67, 0x72, 0x65, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x44, 0x6c, 0x56, 0x63, 0x4a, 0x77, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x44, 0x6c, 0x56, 0x63, 0x4a, 0x77, 0x74, 0x22, 0x81, 0x01,
	0x0a, 0x17, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x43, 0x61, 0x72, 0x41, 0x67, 0x72, 0x65, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x38, 0x0a, 0x17, 0x72, 0x65, 0x6e, 0x74, 0x61,
	0x6c, 0x43, 0x61, 0x72, 0x41, 0x67, 0x72, 0x65, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x56, 0x63, 0x4a,
	0x77, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x17, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c,
	0x43, 0x61, 0x72, 0x41, 0x67, 0x72, 0x65, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x56, 0x63, 0x4a, 0x77,
	0x74, 0x22, 0x53, 0x0a, 0x17, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x43, 0x61, 0x72, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x17,
	0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x43, 0x61, 0x72, 0x41, 0x67, 0x72, 0x65, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x56, 0x63, 0x4a, 0x77, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x17, 0x72,
	0x65, 0x6e, 0x74, 0x61, 0x6c, 0x43, 0x61, 0x72, 0x41, 0x67, 0x72, 0x65, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x56, 0x63, 0x4a, 0x77, 0x74, 0x22, 0x45, 0x0a, 0x15, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c,
	0x43, 0x61, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x8a, 0x03,
	0x0a, 0x06, 0x49, 0x73, 0x73, 0x75, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x19, 0x2e,
	0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65,
	0x72, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x43, 0x72, 0x65, 0x64, 0x49, 0x64,
	0x43, 0x61, 0x72, 0x64, 0x12, 0x15, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2e, 0x49, 0x64,
	0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x69, 0x73,
	0x73, 0x75, 0x65, 0x72, 0x2e, 0x49, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x43, 0x72, 0x65, 0x64, 0x44, 0x6c, 0x43,
	0x61, 0x72, 0x64, 0x12, 0x15, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2e, 0x44, 0x6c, 0x43,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x69, 0x73, 0x73,
	0x75, 0x65, 0x72, 0x2e, 0x44, 0x6c, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x61, 0x0a, 0x19, 0x52, 0x65, 0x71, 0x43, 0x72, 0x65, 0x64, 0x52, 0x65, 0x6e, 0x74,
	0x61, 0x6c, 0x43, 0x61, 0x72, 0x41, 0x67, 0x72, 0x65, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x21,
	0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x43, 0x61,
	0x72, 0x41, 0x67, 0x72, 0x65, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x6e, 0x74, 0x61,
	0x6c, 0x43, 0x61, 0x72, 0x41, 0x67, 0x72, 0x65, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x10, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x43, 0x61,
	0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x1f, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x43, 0x61, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x69, 0x73, 0x73, 0x75,
	0x65, 0x72, 0x2e, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x43, 0x61, 0x72, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x6a, 0x0a, 0x1c, 0x69, 0x6f,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x42, 0x0f, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x37, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2d, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_files_issuer_proto_rawDescOnce sync.Once
	file_proto_files_issuer_proto_rawDescData = file_proto_files_issuer_proto_rawDesc
)

func file_proto_files_issuer_proto_rawDescGZIP() []byte {
	file_proto_files_issuer_proto_rawDescOnce.Do(func() {
		file_proto_files_issuer_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_files_issuer_proto_rawDescData)
	})
	return file_proto_files_issuer_proto_rawDescData
}

var file_proto_files_issuer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_files_issuer_proto_goTypes = []interface{}{
	(*CredentialRequest)(nil),         // 0: issuer.CredentialRequest
	(*CredentialReply)(nil),           // 1: issuer.CredentialReply
	(*IdCardRequest)(nil),             // 2: issuer.IdCardRequest
	(*IdCardReply)(nil),               // 3: issuer.IdCardReply
	(*DlCardRequest)(nil),             // 4: issuer.DlCardRequest
	(*DlCardReply)(nil),               // 5: issuer.DlCardReply
	(*RentalCarAgreementRequest)(nil), // 6: issuer.RentalCarAgreementRequest
	(*RentalCarAgreementReply)(nil),   // 7: issuer.RentalCarAgreementReply
	(*RentalCarControlRequest)(nil),   // 8: issuer.RentalCarControlRequest
	(*RentalCarControlReply)(nil),     // 9: issuer.RentalCarControlReply
}
var file_proto_files_issuer_proto_depIdxs = []int32{
	0, // 0: issuer.Issuer.RequestCredential:input_type -> issuer.CredentialRequest
	2, // 1: issuer.Issuer.ReqCredIdCard:input_type -> issuer.IdCardRequest
	4, // 2: issuer.Issuer.ReqCredDlCard:input_type -> issuer.DlCardRequest
	6, // 3: issuer.Issuer.ReqCredRentalCarAgreement:input_type -> issuer.RentalCarAgreementRequest
	8, // 4: issuer.Issuer.RentalCarControl:input_type -> issuer.RentalCarControlRequest
	1, // 5: issuer.Issuer.RequestCredential:output_type -> issuer.CredentialReply
	3, // 6: issuer.Issuer.ReqCredIdCard:output_type -> issuer.IdCardReply
	5, // 7: issuer.Issuer.ReqCredDlCard:output_type -> issuer.DlCardReply
	7, // 8: issuer.Issuer.ReqCredRentalCarAgreement:output_type -> issuer.RentalCarAgreementReply
	9, // 9: issuer.Issuer.RentalCarControl:output_type -> issuer.RentalCarControlReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_files_issuer_proto_init() }
func file_proto_files_issuer_proto_init() {
	if File_proto_files_issuer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_files_issuer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredentialRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_issuer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredentialReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_issuer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_issuer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdCardReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_issuer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DlCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_issuer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DlCardReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_issuer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RentalCarAgreementRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_issuer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RentalCarAgreementReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_issuer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RentalCarControlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_issuer_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RentalCarControlReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_files_issuer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_files_issuer_proto_goTypes,
		DependencyIndexes: file_proto_files_issuer_proto_depIdxs,
		MessageInfos:      file_proto_files_issuer_proto_msgTypes,
	}.Build()
	File_proto_files_issuer_proto = out.File
	file_proto_files_issuer_proto_rawDesc = nil
	file_proto_files_issuer_proto_goTypes = nil
	file_proto_files_issuer_proto_depIdxs = nil
}
