// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto-files/issuer.proto

package proto_files

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VcClaimJwt    string                 `protobuf:"bytes,1,opt,name=vc_claim_jwt,json=vcClaimJwt,proto3" json:"vc_claim_jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialRequest) Reset() {
	*x = CredentialRequest{}
	mi := &file_proto_files_issuer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialRequest) ProtoMessage() {}

func (x *CredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_issuer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialRequest.ProtoReflect.Descriptor instead.
func (*CredentialRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_issuer_proto_rawDescGZIP(), []int{0}
}

func (x *CredentialRequest) GetVcClaimJwt() string {
	if x != nil {
		return x.VcClaimJwt
	}
	return ""
}

type CredentialReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VcJwt         string                 `protobuf:"bytes,1,opt,name=vc_jwt,json=vcJwt,proto3" json:"vc_jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialReply) Reset() {
	*x = CredentialReply{}
	mi := &file_proto_files_issuer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialReply) ProtoMessage() {}

func (x *CredentialReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_issuer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialReply.ProtoReflect.Descriptor instead.
func (*CredentialReply) Descriptor() ([]byte, []int) {
	return file_proto_files_issuer_proto_rawDescGZIP(), []int{1}
}

func (x *CredentialReply) GetVcJwt() string {
	if x != nil {
		return x.VcJwt
	}
	return ""
}

type IdCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdCardRequest) Reset() {
	*x = IdCardRequest{}
	mi := &file_proto_files_issuer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdCardRequest) ProtoMessage() {}

func (x *IdCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_issuer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdCardRequest.ProtoReflect.Descriptor instead.
func (*IdCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_issuer_proto_rawDescGZIP(), []int{2}
}

func (x *IdCardRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type IdCardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EidVcJwt      string                 `protobuf:"bytes,1,opt,name=eid_vc_jwt,json=eidVcJwt,proto3" json:"eid_vc_jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdCardReply) Reset() {
	*x = IdCardReply{}
	mi := &file_proto_files_issuer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdCardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdCardReply) ProtoMessage() {}

func (x *IdCardReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_issuer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdCardReply.ProtoReflect.Descriptor instead.
func (*IdCardReply) Descriptor() ([]byte, []int) {
	return file_proto_files_issuer_proto_rawDescGZIP(), []int{3}
}

func (x *IdCardReply) GetEidVcJwt() string {
	if x != nil {
		return x.EidVcJwt
	}
	return ""
}

type DlCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EidVcJwt      string                 `protobuf:"bytes,1,opt,name=eid_vc_jwt,json=eidVcJwt,proto3" json:"eid_vc_jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DlCardRequest) Reset() {
	*x = DlCardRequest{}
	mi := &file_proto_files_issuer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DlCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DlCardRequest) ProtoMessage() {}

func (x *DlCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_issuer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DlCardRequest.ProtoReflect.Descriptor instead.
func (*DlCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_issuer_proto_rawDescGZIP(), []int{4}
}

func (x *DlCardRequest) GetEidVcJwt() string {
	if x != nil {
		return x.EidVcJwt
	}
	return ""
}

type DlCardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	EdlVcJwt      string                 `protobuf:"bytes,3,opt,name=edl_vc_jwt,json=edlVcJwt,proto3" json:"edl_vc_jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DlCardReply) Reset() {
	*x = DlCardReply{}
	mi := &file_proto_files_issuer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DlCardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DlCardReply) ProtoMessage() {}

func (x *DlCardReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_issuer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DlCardReply.ProtoReflect.Descriptor instead.
func (*DlCardReply) Descriptor() ([]byte, []int) {
	return file_proto_files_issuer_proto_rawDescGZIP(), []int{5}
}

func (x *DlCardReply) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *DlCardReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *DlCardReply) GetEdlVcJwt() string {
	if x != nil {
		return x.EdlVcJwt
	}
	return ""
}

type RentalCarAgreementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdlVcJwt      string                 `protobuf:"bytes,1,opt,name=edl_vc_jwt,json=edlVcJwt,proto3" json:"edl_vc_jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RentalCarAgreementRequest) Reset() {
	*x = RentalCarAgreementRequest{}
	mi := &file_proto_files_issuer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RentalCarAgreementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RentalCarAgreementRequest) ProtoMessage() {}

func (x *RentalCarAgreementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_issuer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RentalCarAgreementRequest.ProtoReflect.Descriptor instead.
func (*RentalCarAgreementRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_issuer_proto_rawDescGZIP(), []int{6}
}

func (x *RentalCarAgreementRequest) GetEdlVcJwt() string {
	if x != nil {
		return x.EdlVcJwt
	}
	return ""
}

type RentalCarAgreementReply struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Valid                   bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Result                  string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	RentalCarAgreementVcJwt string                 `protobuf:"bytes,3,opt,name=rental_car_agreement_vc_jwt,json=rentalCarAgreementVcJwt,proto3" json:"rental_car_agreement_vc_jwt,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RentalCarAgreementReply) Reset() {
	*x = RentalCarAgreementReply{}
	mi := &file_proto_files_issuer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RentalCarAgreementReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RentalCarAgreementReply) ProtoMessage() {}

func (x *RentalCarAgreementReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_issuer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RentalCarAgreementReply.ProtoReflect.Descriptor instead.
func (*RentalCarAgreementReply) Descriptor() ([]byte, []int) {
	return file_proto_files_issuer_proto_rawDescGZIP(), []int{7}
}

func (x *RentalCarAgreementReply) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *RentalCarAgreementReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *RentalCarAgreementReply) GetRentalCarAgreementVcJwt() string {
	if x != nil {
		return x.RentalCarAgreementVcJwt
	}
	return ""
}

type RentalCarControlRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	RentalCarAgreementVcJwt string                 `protobuf:"bytes,1,opt,name=rental_car_agreement_vc_jwt,json=rentalCarAgreementVcJwt,proto3" json:"rental_car_agreement_vc_jwt,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RentalCarControlRequest) Reset() {
	*x = RentalCarControlRequest{}
	mi := &file_proto_files_issuer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RentalCarControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RentalCarControlRequest) ProtoMessage() {}

func (x *RentalCarControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_issuer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RentalCarControlRequest.ProtoReflect.Descriptor instead.
func (*RentalCarControlRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_issuer_proto_rawDescGZIP(), []int{8}
}

func (x *RentalCarControlRequest) GetRentalCarAgreementVcJwt() string {
	if x != nil {
		return x.RentalCarAgreementVcJwt
	}
	return ""
}

type RentalCarControlReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RentalCarControlReply) Reset() {
	*x = RentalCarControlReply{}
	mi := &file_proto_files_issuer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RentalCarControlReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RentalCarControlReply) ProtoMessage() {}

func (x *RentalCarControlReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_issuer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RentalCarControlReply.ProtoReflect.Descriptor instead.
func (*RentalCarControlReply) Descriptor() ([]byte, []int) {
	return file_proto_files_issuer_proto_rawDescGZIP(), []int{9}
}

func (x *RentalCarControlReply) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *RentalCarControlReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_proto_files_issuer_proto protoreflect.FileDescriptor

const file_proto_files_issuer_proto_rawDesc = "" +
	"\n" +
	"\x18proto-files/issuer.proto\x12\x06issuer\"5\n" +
	"\x11CredentialRequest\x12 \n" +
	"\fvc_claim_jwt\x18\x01 \x01(\tR\n" +
	"vcClaimJwt\"(\n" +
	"\x0fCredentialReply\x12\x15\n" +
	"\x06vc_jwt\x18\x01 \x01(\tR\x05vcJwt\"!\n" +
	"\rIdCardRequest\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\"+\n" +
	"\vIdCardReply\x12\x1c\n" +
	"\n" +
	"eid_vc_jwt\x18\x01 \x01(\tR\beidVcJwt\"-\n" +
	"\rDlCardRequest\x12\x1c\n" +
	"\n" +
	"eid_vc_jwt\x18\x01 \x01(\tR\beidVcJwt\"Y\n" +
	"\vDlCardReply\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x1c\n" +
	"\n" +
	"edl_vc_jwt\x18\x03 \x01(\tR\bedlVcJwt\"9\n" +
	"\x19RentalCarAgreementRequest\x12\x1c\n" +
	"\n" +
	"edl_vc_jwt\x18\x01 \x01(\tR\bedlVcJwt\"\x85\x01\n" +
	"\x17RentalCarAgreementReply\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12<\n" +
	"\x1brental_car_agreement_vc_jwt\x18\x03 \x01(\tR\x17rentalCarAgreementVcJwt\"W\n" +
	"\x17RentalCarControlRequest\x12<\n" +
	"\x1brental_car_agreement_vc_jwt\x18\x01 \x01(\tR\x17rentalCarAgreementVcJwt\"E\n" +
	"\x15RentalCarControlReply\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result2\x8a\x03\n" +
	"\x06Issuer\x12I\n" +
	"\x11RequestCredential\x12\x19.issuer.CredentialRequest\x1a\x17.issuer.CredentialReply\"\x00\x12=\n" +
	"\rReqCredIdCard\x12\x15.issuer.IdCardRequest\x1a\x13.issuer.IdCardReply\"\x00\x12=\n" +
	"\rReqCredDlCard\x12\x15.issuer.DlCardRequest\x1a\x13.issuer.DlCardReply\"\x00\x12a\n" +
	"\x19ReqCredRentalCarAgreement\x12!.issuer.RentalCarAgreementRequest\x1a\x1f.issuer.RentalCarAgreementReply\"\x00\x12T\n" +
	"\x10RentalCarControl\x12\x1f.issuer.RentalCarControlRequest\x1a\x1d.issuer.RentalCarControlReply\"\x00BH\n" +
	"\x1cio.grpc.examples.proto-filesB\x0fHelloWorldProtoP\x01Z\x15byd50-ssi/proto-filesb\x06proto3"

var (
	file_proto_files_issuer_proto_rawDescOnce sync.Once
	file_proto_files_issuer_proto_rawDescData []byte
)

func file_proto_files_issuer_proto_rawDescGZIP() []byte {
	file_proto_files_issuer_proto_rawDescOnce.Do(func() {
		file_proto_files_issuer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_files_issuer_proto_rawDesc), len(file_proto_files_issuer_proto_rawDesc)))
	})
	return file_proto_files_issuer_proto_rawDescData
}

var file_proto_files_issuer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_files_issuer_proto_goTypes = []any{
	(*CredentialRequest)(nil),         // 0: issuer.CredentialRequest
	(*CredentialReply)(nil),           // 1: issuer.CredentialReply
	(*IdCardRequest)(nil),             // 2: issuer.IdCardRequest
	(*IdCardReply)(nil),               // 3: issuer.IdCardReply
	(*DlCardRequest)(nil),             // 4: issuer.DlCardRequest
	(*DlCardReply)(nil),               // 5: issuer.DlCardReply
	(*RentalCarAgreementRequest)(nil), // 6: issuer.RentalCarAgreementRequest
	(*RentalCarAgreementReply)(nil),   // 7: issuer.RentalCarAgreementReply
	(*RentalCarControlRequest)(nil),   // 8: issuer.RentalCarControlRequest
	(*RentalCarControlReply)(nil),     // 9: issuer.RentalCarControlReply
}
var file_proto_files_issuer_proto_depIdxs = []int32{
	0, // 0: issuer.Issuer.RequestCredential:input_type -> issuer.CredentialRequest
	2, // 1: issuer.Issuer.ReqCredIdCard:input_type -> issuer.IdCardRequest
	4, // 2: issuer.Issuer.ReqCredDlCard:input_type -> issuer.DlCardRequest
	6, // 3: issuer.Issuer.ReqCredRentalCarAgreement:input_type -> issuer.RentalCarAgreementRequest
	8, // 4: issuer.Issuer.RentalCarControl:input_type -> issuer.RentalCarControlRequest
	1, // 5: issuer.Issuer.RequestCredential:output_type -> issuer.CredentialReply
	3, // 6: issuer.Issuer.ReqCredIdCard:output_type -> issuer.IdCardReply
	5, // 7: issuer.Issuer.ReqCredDlCard:output_type -> issuer.DlCardReply
	7, // 8: issuer.Issuer.ReqCredRentalCarAgreement:output_type -> issuer.RentalCarAgreementReply
	9, // 9: issuer.Issuer.RentalCarControl:output_type -> issuer.RentalCarControlReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_files_issuer_proto_init() }
func file_proto_files_issuer_proto_init() {
	if File_proto_files_issuer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_files_issuer_proto_rawDesc), len(file_proto_files_issuer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_files_issuer_proto_goTypes,
		DependencyIndexes: file_proto_files_issuer_proto_depIdxs,
		MessageInfos:      file_proto_files_issuer_proto_msgTypes,
	}.Build()
	File_proto_files_issuer_proto = out.File
	file_proto_files_issuer_proto_goTypes = nil
	file_proto_files_issuer_proto_depIdxs = nil
}
