// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: proto-files/issuer.proto

package proto_files

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Issuer_RequestCredential_FullMethodName         = "/issuer.Issuer/RequestCredential"
	Issuer_ReqCredIdCard_FullMethodName             = "/issuer.Issuer/ReqCredIdCard"
	Issuer_ReqCredDlCard_FullMethodName             = "/issuer.Issuer/ReqCredDlCard"
	Issuer_ReqCredRentalCarAgreement_FullMethodName = "/issuer.Issuer/ReqCredRentalCarAgreement"
	Issuer_RentalCarControl_FullMethodName          = "/issuer.Issuer/RentalCarControl"
)

// IssuerClient is the client API for Issuer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IssuerClient interface {
	RequestCredential(ctx context.Context, in *CredentialRequest, opts ...grpc.CallOption) (*CredentialReply, error)
	ReqCredIdCard(ctx context.Context, in *IdCardRequest, opts ...grpc.CallOption) (*IdCardReply, error)
	ReqCredDlCard(ctx context.Context, in *DlCardRequest, opts ...grpc.CallOption) (*DlCardReply, error)
	ReqCredRentalCarAgreement(ctx context.Context, in *RentalCarAgreementRequest, opts ...grpc.CallOption) (*RentalCarAgreementReply, error)
	RentalCarControl(ctx context.Context, in *RentalCarControlRequest, opts ...grpc.CallOption) (*RentalCarControlReply, error)
}

type issuerClient struct {
	cc grpc.ClientConnInterface
}

func NewIssuerClient(cc grpc.ClientConnInterface) IssuerClient {
	return &issuerClient{cc}
}

func (c *issuerClient) RequestCredential(ctx context.Context, in *CredentialRequest, opts ...grpc.CallOption) (*CredentialReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialReply)
	err := c.cc.Invoke(ctx, Issuer_RequestCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issuerClient) ReqCredIdCard(ctx context.Context, in *IdCardRequest, opts ...grpc.CallOption) (*IdCardReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdCardReply)
	err := c.cc.Invoke(ctx, Issuer_ReqCredIdCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issuerClient) ReqCredDlCard(ctx context.Context, in *DlCardRequest, opts ...grpc.CallOption) (*DlCardReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DlCardReply)
	err := c.cc.Invoke(ctx, Issuer_ReqCredDlCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issuerClient) ReqCredRentalCarAgreement(ctx context.Context, in *RentalCarAgreementRequest, opts ...grpc.CallOption) (*RentalCarAgreementReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RentalCarAgreementReply)
	err := c.cc.Invoke(ctx, Issuer_ReqCredRentalCarAgreement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issuerClient) RentalCarControl(ctx context.Context, in *RentalCarControlRequest, opts ...grpc.CallOption) (*RentalCarControlReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RentalCarControlReply)
	err := c.cc.Invoke(ctx, Issuer_RentalCarControl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IssuerServer is the server API for Issuer service.
// All implementations must embed UnimplementedIssuerServer
// for forward compatibility.
type IssuerServer interface {
	RequestCredential(context.Context, *CredentialRequest) (*CredentialReply, error)
	ReqCredIdCard(context.Context, *IdCardRequest) (*IdCardReply, error)
	ReqCredDlCard(context.Context, *DlCardRequest) (*DlCardReply, error)
	ReqCredRentalCarAgreement(context.Context, *RentalCarAgreementRequest) (*RentalCarAgreementReply, error)
	RentalCarControl(context.Context, *RentalCarControlRequest) (*RentalCarControlReply, error)
	mustEmbedUnimplementedIssuerServer()
}

// UnimplementedIssuerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIssuerServer struct{}

func (UnimplementedIssuerServer) RequestCredential(context.Context, *CredentialRequest) (*CredentialReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestCredential not implemented")
}
func (UnimplementedIssuerServer) ReqCredIdCard(context.Context, *IdCardRequest) (*IdCardReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ReqCredIdCard not implemented")
}
func (UnimplementedIssuerServer) ReqCredDlCard(context.Context, *DlCardRequest) (*DlCardReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ReqCredDlCard not implemented")
}
func (UnimplementedIssuerServer) ReqCredRentalCarAgreement(context.Context, *RentalCarAgreementRequest) (*RentalCarAgreementReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ReqCredRentalCarAgreement not implemented")
}
func (UnimplementedIssuerServer) RentalCarControl(context.Context, *RentalCarControlRequest) (*RentalCarControlReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RentalCarControl not implemented")
}
func (UnimplementedIssuerServer) mustEmbedUnimplementedIssuerServer() {}
func (UnimplementedIssuerServer) testEmbeddedByValue()                {}

// UnsafeIssuerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IssuerServer will
// result in compilation errors.
type UnsafeIssuerServer interface {
	mustEmbedUnimplementedIssuerServer()
}

func RegisterIssuerServer(s grpc.ServiceRegistrar, srv IssuerServer) {
	// If the following call panics, it indicates UnimplementedIssuerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Issuer_ServiceDesc, srv)
}

func _Issuer_RequestCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServer).RequestCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Issuer_RequestCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServer).RequestCredential(ctx, req.(*CredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Issuer_ReqCredIdCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServer).ReqCredIdCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Issuer_ReqCredIdCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServer).ReqCredIdCard(ctx, req.(*IdCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Issuer_ReqCredDlCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DlCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServer).ReqCredDlCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Issuer_ReqCredDlCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServer).ReqCredDlCard(ctx, req.(*DlCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Issuer_ReqCredRentalCarAgreement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RentalCarAgreementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServer).ReqCredRentalCarAgreement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Issuer_ReqCredRentalCarAgreement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServer).ReqCredRentalCarAgreement(ctx, req.(*RentalCarAgreementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Issuer_RentalCarControl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RentalCarControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServer).RentalCarControl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Issuer_RentalCarControl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServer).RentalCarControl(ctx, req.(*RentalCarControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Issuer_ServiceDesc is the grpc.ServiceDesc for Issuer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Issuer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "issuer.Issuer",
	HandlerType: (*IssuerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestCredential",
			Handler:    _Issuer_RequestCredential_Handler,
		},
		{
			MethodName: "ReqCredIdCard",
			Handler:    _Issuer_ReqCredIdCard_Handler,
		},
		{
			MethodName: "ReqCredDlCard",
			Handler:    _Issuer_ReqCredDlCard_Handler,
		},
		{
			MethodName: "ReqCredRentalCarAgreement",
			Handler:    _Issuer_ReqCredRentalCarAgreement_Handler,
		},
		{
			MethodName: "RentalCarControl",
			Handler:    _Issuer_RentalCarControl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto-files/issuer.proto",
}
