// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: proto-files/registry.proto

package proto_files

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Registry_CreateDid_FullMethodName  = "/registry.Registry/CreateDid"
	Registry_ResolveDid_FullMethodName = "/registry.Registry/ResolveDid"
	Registry_UpdateDid_FullMethodName  = "/registry.Registry/UpdateDid"
)

// RegistryClient is the client API for Registry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistryClient interface {
	CreateDid(ctx context.Context, in *RegistryCreateDidRequest, opts ...grpc.CallOption) (*RegistryCreateDidResponse, error)
	// rpc RegisterDid (RegistryRegisterDidRequest) returns (RegistryRegisterDidResponse) {}
	ResolveDid(ctx context.Context, in *RegistryResolveDidRequest, opts ...grpc.CallOption) (*RegistryResolveDidResponse, error)
	UpdateDid(ctx context.Context, in *RegistryUpdateDidRequest, opts ...grpc.CallOption) (*RegistryUpdateDidResponse, error)
}

type registryClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryClient(cc grpc.ClientConnInterface) RegistryClient {
	return &registryClient{cc}
}

func (c *registryClient) CreateDid(ctx context.Context, in *RegistryCreateDidRequest, opts ...grpc.CallOption) (*RegistryCreateDidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryCreateDidResponse)
	err := c.cc.Invoke(ctx, Registry_CreateDid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) ResolveDid(ctx context.Context, in *RegistryResolveDidRequest, opts ...grpc.CallOption) (*RegistryResolveDidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryResolveDidResponse)
	err := c.cc.Invoke(ctx, Registry_ResolveDid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) UpdateDid(ctx context.Context, in *RegistryUpdateDidRequest, opts ...grpc.CallOption) (*RegistryUpdateDidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryUpdateDidResponse)
	err := c.cc.Invoke(ctx, Registry_UpdateDid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServer is the server API for Registry service.
// All implementations must embed UnimplementedRegistryServer
// for forward compatibility.
type RegistryServer interface {
	CreateDid(context.Context, *RegistryCreateDidRequest) (*RegistryCreateDidResponse, error)
	// rpc RegisterDid (RegistryRegisterDidRequest) returns (RegistryRegisterDidResponse) {}
	ResolveDid(context.Context, *RegistryResolveDidRequest) (*RegistryResolveDidResponse, error)
	UpdateDid(context.Context, *RegistryUpdateDidRequest) (*RegistryUpdateDidResponse, error)
	mustEmbedUnimplementedRegistryServer()
}

// UnimplementedRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistryServer struct{}

func (UnimplementedRegistryServer) CreateDid(context.Context, *RegistryCreateDidRequest) (*RegistryCreateDidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDid not implemented")
}
func (UnimplementedRegistryServer) ResolveDid(context.Context, *RegistryResolveDidRequest) (*RegistryResolveDidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveDid not implemented")
}
func (UnimplementedRegistryServer) UpdateDid(context.Context, *RegistryUpdateDidRequest) (*RegistryUpdateDidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDid not implemented")
}
func (UnimplementedRegistryServer) mustEmbedUnimplementedRegistryServer() {}
func (UnimplementedRegistryServer) testEmbeddedByValue()                  {}

// UnsafeRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistryServer will
// result in compilation errors.
type UnsafeRegistryServer interface {
	mustEmbedUnimplementedRegistryServer()
}

func RegisterRegistryServer(s grpc.ServiceRegistrar, srv RegistryServer) {
	// If the following call panics, it indicates UnimplementedRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Registry_ServiceDesc, srv)
}

func _Registry_CreateDid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryCreateDidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).CreateDid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registry_CreateDid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).CreateDid(ctx, req.(*RegistryCreateDidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_ResolveDid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryResolveDidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).ResolveDid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registry_ResolveDid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).ResolveDid(ctx, req.(*RegistryResolveDidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_UpdateDid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryUpdateDidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).UpdateDid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registry_UpdateDid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).UpdateDid(ctx, req.(*RegistryUpdateDidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Registry_ServiceDesc is the grpc.ServiceDesc for Registry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Registry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "registry.Registry",
	HandlerType: (*RegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDid",
			Handler:    _Registry_CreateDid_Handler,
		},
		{
			MethodName: "ResolveDid",
			Handler:    _Registry_ResolveDid_Handler,
		},
		{
			MethodName: "UpdateDid",
			Handler:    _Registry_UpdateDid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto-files/registry.proto",
}
