// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: proto-files/registrar.proto

package proto_files

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Registrar_CreateDid_FullMethodName   = "/registrar.Registrar/CreateDid"
	Registrar_RegisterDid_FullMethodName = "/registrar.Registrar/RegisterDid"
	Registrar_ResolveDid_FullMethodName  = "/registrar.Registrar/ResolveDid"
	Registrar_UpdateDid_FullMethodName   = "/registrar.Registrar/UpdateDid"
)

// RegistrarClient is the client API for Registrar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistrarClient interface {
	CreateDid(ctx context.Context, in *CreateDidRequest, opts ...grpc.CallOption) (*CreateDidResponse, error)
	RegisterDid(ctx context.Context, in *RegisterDidRequest, opts ...grpc.CallOption) (*RegisterDidResponse, error)
	ResolveDid(ctx context.Context, in *ResolveDidRequest, opts ...grpc.CallOption) (*ResolveDidResponse, error)
	UpdateDid(ctx context.Context, in *UpdateDidRequest, opts ...grpc.CallOption) (*UpdateDidResponse, error)
}

type registrarClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistrarClient(cc grpc.ClientConnInterface) RegistrarClient {
	return &registrarClient{cc}
}

func (c *registrarClient) CreateDid(ctx context.Context, in *CreateDidRequest, opts ...grpc.CallOption) (*CreateDidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDidResponse)
	err := c.cc.Invoke(ctx, Registrar_CreateDid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrarClient) RegisterDid(ctx context.Context, in *RegisterDidRequest, opts ...grpc.CallOption) (*RegisterDidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDidResponse)
	err := c.cc.Invoke(ctx, Registrar_RegisterDid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrarClient) ResolveDid(ctx context.Context, in *ResolveDidRequest, opts ...grpc.CallOption) (*ResolveDidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveDidResponse)
	err := c.cc.Invoke(ctx, Registrar_ResolveDid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrarClient) UpdateDid(ctx context.Context, in *UpdateDidRequest, opts ...grpc.CallOption) (*UpdateDidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDidResponse)
	err := c.cc.Invoke(ctx, Registrar_UpdateDid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistrarServer is the server API for Registrar service.
// All implementations must embed UnimplementedRegistrarServer
// for forward compatibility.
type RegistrarServer interface {
	CreateDid(context.Context, *CreateDidRequest) (*CreateDidResponse, error)
	RegisterDid(context.Context, *RegisterDidRequest) (*RegisterDidResponse, error)
	ResolveDid(context.Context, *ResolveDidRequest) (*ResolveDidResponse, error)
	UpdateDid(context.Context, *UpdateDidRequest) (*UpdateDidResponse, error)
	mustEmbedUnimplementedRegistrarServer()
}

// UnimplementedRegistrarServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistrarServer struct{}

func (UnimplementedRegistrarServer) CreateDid(context.Context, *CreateDidRequest) (*CreateDidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDid not implemented")
}
func (UnimplementedRegistrarServer) RegisterDid(context.Context, *RegisterDidRequest) (*RegisterDidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDid not implemented")
}
func (UnimplementedRegistrarServer) ResolveDid(context.Context, *ResolveDidRequest) (*ResolveDidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveDid not implemented")
}
func (UnimplementedRegistrarServer) UpdateDid(context.Context, *UpdateDidRequest) (*UpdateDidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDid not implemented")
}
func (UnimplementedRegistrarServer) mustEmbedUnimplementedRegistrarServer() {}
func (UnimplementedRegistrarServer) testEmbeddedByValue()                   {}

// UnsafeRegistrarServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistrarServer will
// result in compilation errors.
type UnsafeRegistrarServer interface {
	mustEmbedUnimplementedRegistrarServer()
}

func RegisterRegistrarServer(s grpc.ServiceRegistrar, srv RegistrarServer) {
	// If the following call panics, it indicates UnimplementedRegistrarServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Registrar_ServiceDesc, srv)
}

func _Registrar_CreateDid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrarServer).CreateDid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registrar_CreateDid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrarServer).CreateDid(ctx, req.(*CreateDidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registrar_RegisterDid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrarServer).RegisterDid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registrar_RegisterDid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrarServer).RegisterDid(ctx, req.(*RegisterDidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registrar_ResolveDid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveDidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrarServer).ResolveDid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registrar_ResolveDid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrarServer).ResolveDid(ctx, req.(*ResolveDidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registrar_UpdateDid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrarServer).UpdateDid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registrar_UpdateDid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrarServer).UpdateDid(ctx, req.(*UpdateDidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Registrar_ServiceDesc is the grpc.ServiceDesc for Registrar service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Registrar_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "registrar.Registrar",
	HandlerType: (*RegistrarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDid",
			Handler:    _Registrar_CreateDid_Handler,
		},
		{
			MethodName: "RegisterDid",
			Handler:    _Registrar_RegisterDid_Handler,
		},
		{
			MethodName: "ResolveDid",
			Handler:    _Registrar_ResolveDid_Handler,
		},
		{
			MethodName: "UpdateDid",
			Handler:    _Registrar_UpdateDid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto-files/registrar.proto",
}
