// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto-files/registry.proto

package proto_files

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RegistryClient is the client API for Registry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistryClient interface {
	// Sends a request to generate DIDs.
	ScCreateDID(ctx context.Context, in *ScCreateDIDsRequest, opts ...grpc.CallOption) (*ScCreateDIDsReply, error)
	// TBD
	//rpc scRegisterDID (scRegisterDIDsRequest) returns (scRegisterDIDsReply) {}
	ScResolveDID(ctx context.Context, in *ScResolveDIDsRequest, opts ...grpc.CallOption) (*ScResolveDIDsReply, error)
	ScUpdateDID(ctx context.Context, in *ScUpdateDIDsRequest, opts ...grpc.CallOption) (*ScUpdateDIDsReply, error)
}

type registryClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryClient(cc grpc.ClientConnInterface) RegistryClient {
	return &registryClient{cc}
}

func (c *registryClient) ScCreateDID(ctx context.Context, in *ScCreateDIDsRequest, opts ...grpc.CallOption) (*ScCreateDIDsReply, error) {
	out := new(ScCreateDIDsReply)
	err := c.cc.Invoke(ctx, "/registry.Registry/scCreateDID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) ScResolveDID(ctx context.Context, in *ScResolveDIDsRequest, opts ...grpc.CallOption) (*ScResolveDIDsReply, error) {
	out := new(ScResolveDIDsReply)
	err := c.cc.Invoke(ctx, "/registry.Registry/scResolveDID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) ScUpdateDID(ctx context.Context, in *ScUpdateDIDsRequest, opts ...grpc.CallOption) (*ScUpdateDIDsReply, error) {
	out := new(ScUpdateDIDsReply)
	err := c.cc.Invoke(ctx, "/registry.Registry/scUpdateDID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServer is the server API for Registry service.
// All implementations must embed UnimplementedRegistryServer
// for forward compatibility
type RegistryServer interface {
	// Sends a request to generate DIDs.
	ScCreateDID(context.Context, *ScCreateDIDsRequest) (*ScCreateDIDsReply, error)
	// TBD
	//rpc scRegisterDID (scRegisterDIDsRequest) returns (scRegisterDIDsReply) {}
	ScResolveDID(context.Context, *ScResolveDIDsRequest) (*ScResolveDIDsReply, error)
	ScUpdateDID(context.Context, *ScUpdateDIDsRequest) (*ScUpdateDIDsReply, error)
	mustEmbedUnimplementedRegistryServer()
}

// UnimplementedRegistryServer must be embedded to have forward compatible implementations.
type UnimplementedRegistryServer struct {
}

func (UnimplementedRegistryServer) ScCreateDID(context.Context, *ScCreateDIDsRequest) (*ScCreateDIDsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScCreateDID not implemented")
}
func (UnimplementedRegistryServer) ScResolveDID(context.Context, *ScResolveDIDsRequest) (*ScResolveDIDsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScResolveDID not implemented")
}
func (UnimplementedRegistryServer) ScUpdateDID(context.Context, *ScUpdateDIDsRequest) (*ScUpdateDIDsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScUpdateDID not implemented")
}
func (UnimplementedRegistryServer) mustEmbedUnimplementedRegistryServer() {}

// UnsafeRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistryServer will
// result in compilation errors.
type UnsafeRegistryServer interface {
	mustEmbedUnimplementedRegistryServer()
}

func RegisterRegistryServer(s grpc.ServiceRegistrar, srv RegistryServer) {
	s.RegisterService(&Registry_ServiceDesc, srv)
}

func _Registry_ScCreateDID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScCreateDIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).ScCreateDID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.Registry/scCreateDID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).ScCreateDID(ctx, req.(*ScCreateDIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_ScResolveDID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScResolveDIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).ScResolveDID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.Registry/scResolveDID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).ScResolveDID(ctx, req.(*ScResolveDIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_ScUpdateDID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScUpdateDIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).ScUpdateDID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.Registry/scUpdateDID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).ScUpdateDID(ctx, req.(*ScUpdateDIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Registry_ServiceDesc is the grpc.ServiceDesc for Registry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Registry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "registry.Registry",
	HandlerType: (*RegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "scCreateDID",
			Handler:    _Registry_ScCreateDID_Handler,
		},
		{
			MethodName: "scResolveDID",
			Handler:    _Registry_ScResolveDID_Handler,
		},
		{
			MethodName: "scUpdateDID",
			Handler:    _Registry_ScUpdateDID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto-files/registry.proto",
}
