// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto-files/registry.proto

package proto_files

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the publicKey.
type ScCreateDIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey string `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
}

func (x *ScCreateDIDsRequest) Reset() {
	*x = ScCreateDIDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_registry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScCreateDIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScCreateDIDsRequest) ProtoMessage() {}

func (x *ScCreateDIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScCreateDIDsRequest.ProtoReflect.Descriptor instead.
func (*ScCreateDIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_registry_proto_rawDescGZIP(), []int{0}
}

func (x *ScCreateDIDsRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

// The response message containing the created DID.
type ScCreateDIDsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (x *ScCreateDIDsReply) Reset() {
	*x = ScCreateDIDsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_registry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScCreateDIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScCreateDIDsReply) ProtoMessage() {}

func (x *ScCreateDIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScCreateDIDsReply.ProtoReflect.Descriptor instead.
func (*ScCreateDIDsReply) Descriptor() ([]byte, []int) {
	return file_proto_files_registry_proto_rawDescGZIP(), []int{1}
}

func (x *ScCreateDIDsReply) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

// The request message containing the publicKey.
type ScRegisterDIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did      string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Document string `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
}

func (x *ScRegisterDIDsRequest) Reset() {
	*x = ScRegisterDIDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_registry_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScRegisterDIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScRegisterDIDsRequest) ProtoMessage() {}

func (x *ScRegisterDIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registry_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScRegisterDIDsRequest.ProtoReflect.Descriptor instead.
func (*ScRegisterDIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_registry_proto_rawDescGZIP(), []int{2}
}

func (x *ScRegisterDIDsRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *ScRegisterDIDsRequest) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

// The response message containing the result.
type ScRegisterDIDsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ScRegisterDIDsReply) Reset() {
	*x = ScRegisterDIDsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_registry_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScRegisterDIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScRegisterDIDsReply) ProtoMessage() {}

func (x *ScRegisterDIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registry_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScRegisterDIDsReply.ProtoReflect.Descriptor instead.
func (*ScRegisterDIDsReply) Descriptor() ([]byte, []int) {
	return file_proto_files_registry_proto_rawDescGZIP(), []int{3}
}

func (x *ScRegisterDIDsReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// The request message containing the DID.
type ScResolveDIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (x *ScResolveDIDsRequest) Reset() {
	*x = ScResolveDIDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_registry_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScResolveDIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScResolveDIDsRequest) ProtoMessage() {}

func (x *ScResolveDIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registry_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScResolveDIDsRequest.ProtoReflect.Descriptor instead.
func (*ScResolveDIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_registry_proto_rawDescGZIP(), []int{4}
}

func (x *ScResolveDIDsRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

// The response message containing the DID document.
type ScResolveDIDsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResolutionError     string `protobuf:"bytes,1,opt,name=resolutionError,proto3" json:"resolutionError,omitempty"`
	DidDocument         string `protobuf:"bytes,2,opt,name=didDocument,proto3" json:"didDocument,omitempty"`
	DidDocumentMetadata string `protobuf:"bytes,3,opt,name=didDocumentMetadata,proto3" json:"didDocumentMetadata,omitempty"`
}

func (x *ScResolveDIDsReply) Reset() {
	*x = ScResolveDIDsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_registry_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScResolveDIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScResolveDIDsReply) ProtoMessage() {}

func (x *ScResolveDIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registry_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScResolveDIDsReply.ProtoReflect.Descriptor instead.
func (*ScResolveDIDsReply) Descriptor() ([]byte, []int) {
	return file_proto_files_registry_proto_rawDescGZIP(), []int{5}
}

func (x *ScResolveDIDsReply) GetResolutionError() string {
	if x != nil {
		return x.ResolutionError
	}
	return ""
}

func (x *ScResolveDIDsReply) GetDidDocument() string {
	if x != nil {
		return x.DidDocument
	}
	return ""
}

func (x *ScResolveDIDsReply) GetDidDocumentMetadata() string {
	if x != nil {
		return x.DidDocumentMetadata
	}
	return ""
}

// The request message containing the DID & document.
type ScUpdateDIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did      string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Document string `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
}

func (x *ScUpdateDIDsRequest) Reset() {
	*x = ScUpdateDIDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_registry_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScUpdateDIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScUpdateDIDsRequest) ProtoMessage() {}

func (x *ScUpdateDIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registry_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScUpdateDIDsRequest.ProtoReflect.Descriptor instead.
func (*ScUpdateDIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_registry_proto_rawDescGZIP(), []int{6}
}

func (x *ScUpdateDIDsRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *ScUpdateDIDsRequest) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

// The response message containing the result.
type ScUpdateDIDsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ScUpdateDIDsReply) Reset() {
	*x = ScUpdateDIDsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_registry_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScUpdateDIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScUpdateDIDsReply) ProtoMessage() {}

func (x *ScUpdateDIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registry_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScUpdateDIDsReply.ProtoReflect.Descriptor instead.
func (*ScUpdateDIDsReply) Descriptor() ([]byte, []int) {
	return file_proto_files_registry_proto_rawDescGZIP(), []int{7}
}

func (x *ScUpdateDIDsReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_proto_files_registry_proto protoreflect.FileDescriptor

var file_proto_files_registry_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x22, 0x33, 0x0a, 0x13, 0x73, 0x63, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x25, 0x0a, 0x11, 0x73,
	0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64,
	0x69, 0x64, 0x22, 0x45, 0x0a, 0x15, 0x73, 0x63, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x2d, 0x0a, 0x13, 0x73, 0x63, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x28, 0x0a, 0x14, 0x73, 0x63, 0x52, 0x65,
	0x73, 0x6f, 0x6c, 0x76, 0x65, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64,
	0x69, 0x64, 0x22, 0x92, 0x01, 0x0a, 0x12, 0x73, 0x63, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65,
	0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x73,
	0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x64, 0x44, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x13, 0x64, 0x69, 0x64, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x13, 0x64, 0x69, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x43, 0x0a, 0x13, 0x73, 0x63, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x2b, 0x0a, 0x11,
	0x73, 0x63, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xf4, 0x01, 0x0a, 0x08, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x12, 0x4b, 0x0a, 0x0b, 0x73, 0x63, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x49, 0x44, 0x12, 0x1d, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79,
	0x2e, 0x73, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e,
	0x73, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0c, 0x73, 0x63, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65,
	0x44, 0x49, 0x44, 0x12, 0x1e, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x73,
	0x63, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x73,
	0x63, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0b, 0x73, 0x63, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44,
	0x49, 0x44, 0x12, 0x1d, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x73, 0x63,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x73, 0x63, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x42, 0x6a, 0x0a, 0x1c, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x42, 0x0f, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x37, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61,
	0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_files_registry_proto_rawDescOnce sync.Once
	file_proto_files_registry_proto_rawDescData = file_proto_files_registry_proto_rawDesc
)

func file_proto_files_registry_proto_rawDescGZIP() []byte {
	file_proto_files_registry_proto_rawDescOnce.Do(func() {
		file_proto_files_registry_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_files_registry_proto_rawDescData)
	})
	return file_proto_files_registry_proto_rawDescData
}

var file_proto_files_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_files_registry_proto_goTypes = []interface{}{
	(*ScCreateDIDsRequest)(nil),   // 0: registry.scCreateDIDsRequest
	(*ScCreateDIDsReply)(nil),     // 1: registry.scCreateDIDsReply
	(*ScRegisterDIDsRequest)(nil), // 2: registry.scRegisterDIDsRequest
	(*ScRegisterDIDsReply)(nil),   // 3: registry.scRegisterDIDsReply
	(*ScResolveDIDsRequest)(nil),  // 4: registry.scResolveDIDsRequest
	(*ScResolveDIDsReply)(nil),    // 5: registry.scResolveDIDsReply
	(*ScUpdateDIDsRequest)(nil),   // 6: registry.scUpdateDIDsRequest
	(*ScUpdateDIDsReply)(nil),     // 7: registry.scUpdateDIDsReply
}
var file_proto_files_registry_proto_depIdxs = []int32{
	0, // 0: registry.Registry.scCreateDID:input_type -> registry.scCreateDIDsRequest
	4, // 1: registry.Registry.scResolveDID:input_type -> registry.scResolveDIDsRequest
	6, // 2: registry.Registry.scUpdateDID:input_type -> registry.scUpdateDIDsRequest
	1, // 3: registry.Registry.scCreateDID:output_type -> registry.scCreateDIDsReply
	5, // 4: registry.Registry.scResolveDID:output_type -> registry.scResolveDIDsReply
	7, // 5: registry.Registry.scUpdateDID:output_type -> registry.scUpdateDIDsReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_files_registry_proto_init() }
func file_proto_files_registry_proto_init() {
	if File_proto_files_registry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_files_registry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScCreateDIDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_registry_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScCreateDIDsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_registry_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScRegisterDIDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_registry_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScRegisterDIDsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_registry_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScResolveDIDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_registry_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScResolveDIDsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_registry_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScUpdateDIDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_registry_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScUpdateDIDsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_files_registry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_files_registry_proto_goTypes,
		DependencyIndexes: file_proto_files_registry_proto_depIdxs,
		MessageInfos:      file_proto_files_registry_proto_msgTypes,
	}.Build()
	File_proto_files_registry_proto = out.File
	file_proto_files_registry_proto_rawDesc = nil
	file_proto_files_registry_proto_goTypes = nil
	file_proto_files_registry_proto_depIdxs = nil
}
