// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto-files/registrar.proto

package proto_files

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RegistrarClient is the client API for Registrar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistrarClient interface {
	// Sends a request to generate DIDs.
	CreateDID(ctx context.Context, in *CreateDIDsRequest, opts ...grpc.CallOption) (*CreateDIDsReply, error)
	RegisterDID(ctx context.Context, in *RegisterDIDsRequest, opts ...grpc.CallOption) (*RegisterDIDsReply, error)
	ResolveDID(ctx context.Context, in *ResolveDIDsRequest, opts ...grpc.CallOption) (*ResolveDIDsReply, error)
	UpdateDID(ctx context.Context, in *UpdateDIDsRequest, opts ...grpc.CallOption) (*UpdateDIDsReply, error)
}

type registrarClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistrarClient(cc grpc.ClientConnInterface) RegistrarClient {
	return &registrarClient{cc}
}

func (c *registrarClient) CreateDID(ctx context.Context, in *CreateDIDsRequest, opts ...grpc.CallOption) (*CreateDIDsReply, error) {
	out := new(CreateDIDsReply)
	err := c.cc.Invoke(ctx, "/registrar.Registrar/createDID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrarClient) RegisterDID(ctx context.Context, in *RegisterDIDsRequest, opts ...grpc.CallOption) (*RegisterDIDsReply, error) {
	out := new(RegisterDIDsReply)
	err := c.cc.Invoke(ctx, "/registrar.Registrar/registerDID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrarClient) ResolveDID(ctx context.Context, in *ResolveDIDsRequest, opts ...grpc.CallOption) (*ResolveDIDsReply, error) {
	out := new(ResolveDIDsReply)
	err := c.cc.Invoke(ctx, "/registrar.Registrar/resolveDID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrarClient) UpdateDID(ctx context.Context, in *UpdateDIDsRequest, opts ...grpc.CallOption) (*UpdateDIDsReply, error) {
	out := new(UpdateDIDsReply)
	err := c.cc.Invoke(ctx, "/registrar.Registrar/updateDID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistrarServer is the server API for Registrar service.
// All implementations must embed UnimplementedRegistrarServer
// for forward compatibility
type RegistrarServer interface {
	// Sends a request to generate DIDs.
	CreateDID(context.Context, *CreateDIDsRequest) (*CreateDIDsReply, error)
	RegisterDID(context.Context, *RegisterDIDsRequest) (*RegisterDIDsReply, error)
	ResolveDID(context.Context, *ResolveDIDsRequest) (*ResolveDIDsReply, error)
	UpdateDID(context.Context, *UpdateDIDsRequest) (*UpdateDIDsReply, error)
	mustEmbedUnimplementedRegistrarServer()
}

// UnimplementedRegistrarServer must be embedded to have forward compatible implementations.
type UnimplementedRegistrarServer struct {
}

func (UnimplementedRegistrarServer) CreateDID(context.Context, *CreateDIDsRequest) (*CreateDIDsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDID not implemented")
}
func (UnimplementedRegistrarServer) RegisterDID(context.Context, *RegisterDIDsRequest) (*RegisterDIDsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDID not implemented")
}
func (UnimplementedRegistrarServer) ResolveDID(context.Context, *ResolveDIDsRequest) (*ResolveDIDsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveDID not implemented")
}
func (UnimplementedRegistrarServer) UpdateDID(context.Context, *UpdateDIDsRequest) (*UpdateDIDsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDID not implemented")
}
func (UnimplementedRegistrarServer) mustEmbedUnimplementedRegistrarServer() {}

// UnsafeRegistrarServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistrarServer will
// result in compilation errors.
type UnsafeRegistrarServer interface {
	mustEmbedUnimplementedRegistrarServer()
}

func RegisterRegistrarServer(s grpc.ServiceRegistrar, srv RegistrarServer) {
	s.RegisterService(&Registrar_ServiceDesc, srv)
}

func _Registrar_CreateDID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrarServer).CreateDID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registrar.Registrar/createDID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrarServer).CreateDID(ctx, req.(*CreateDIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registrar_RegisterDID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrarServer).RegisterDID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registrar.Registrar/registerDID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrarServer).RegisterDID(ctx, req.(*RegisterDIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registrar_ResolveDID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveDIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrarServer).ResolveDID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registrar.Registrar/resolveDID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrarServer).ResolveDID(ctx, req.(*ResolveDIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registrar_UpdateDID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrarServer).UpdateDID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registrar.Registrar/updateDID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrarServer).UpdateDID(ctx, req.(*UpdateDIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Registrar_ServiceDesc is the grpc.ServiceDesc for Registrar service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Registrar_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "registrar.Registrar",
	HandlerType: (*RegistrarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createDID",
			Handler:    _Registrar_CreateDID_Handler,
		},
		{
			MethodName: "registerDID",
			Handler:    _Registrar_RegisterDID_Handler,
		},
		{
			MethodName: "resolveDID",
			Handler:    _Registrar_ResolveDID_Handler,
		},
		{
			MethodName: "updateDID",
			Handler:    _Registrar_UpdateDID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto-files/registrar.proto",
}
