// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto-files/registrar.proto

package proto_files

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDidRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PublicKeyBase58 string                 `protobuf:"bytes,1,opt,name=public_key_base58,json=publicKeyBase58,proto3" json:"public_key_base58,omitempty"`
	Method          string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateDidRequest) Reset() {
	*x = CreateDidRequest{}
	mi := &file_proto_files_registrar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDidRequest) ProtoMessage() {}

func (x *CreateDidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registrar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDidRequest.ProtoReflect.Descriptor instead.
func (*CreateDidRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_registrar_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDidRequest) GetPublicKeyBase58() string {
	if x != nil {
		return x.PublicKeyBase58
	}
	return ""
}

func (x *CreateDidRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type CreateDidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDidResponse) Reset() {
	*x = CreateDidResponse{}
	mi := &file_proto_files_registrar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDidResponse) ProtoMessage() {}

func (x *CreateDidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registrar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDidResponse.ProtoReflect.Descriptor instead.
func (*CreateDidResponse) Descriptor() ([]byte, []int) {
	return file_proto_files_registrar_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDidResponse) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type RegisterDidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Document      string                 `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDidRequest) Reset() {
	*x = RegisterDidRequest{}
	mi := &file_proto_files_registrar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDidRequest) ProtoMessage() {}

func (x *RegisterDidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registrar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDidRequest.ProtoReflect.Descriptor instead.
func (*RegisterDidRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_registrar_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterDidRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *RegisterDidRequest) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

type RegisterDidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDidResponse) Reset() {
	*x = RegisterDidResponse{}
	mi := &file_proto_files_registrar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDidResponse) ProtoMessage() {}

func (x *RegisterDidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registrar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDidResponse.ProtoReflect.Descriptor instead.
func (*RegisterDidResponse) Descriptor() ([]byte, []int) {
	return file_proto_files_registrar_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterDidResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ResolveDidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveDidRequest) Reset() {
	*x = ResolveDidRequest{}
	mi := &file_proto_files_registrar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveDidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDidRequest) ProtoMessage() {}

func (x *ResolveDidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registrar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDidRequest.ProtoReflect.Descriptor instead.
func (*ResolveDidRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_registrar_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveDidRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type ResolveDidResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ResolutionError     string                 `protobuf:"bytes,1,opt,name=resolution_error,json=resolutionError,proto3" json:"resolution_error,omitempty"`
	DidDocument         string                 `protobuf:"bytes,2,opt,name=did_document,json=didDocument,proto3" json:"did_document,omitempty"`
	DidDocumentMetadata string                 `protobuf:"bytes,3,opt,name=did_document_metadata,json=didDocumentMetadata,proto3" json:"did_document_metadata,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ResolveDidResponse) Reset() {
	*x = ResolveDidResponse{}
	mi := &file_proto_files_registrar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveDidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDidResponse) ProtoMessage() {}

func (x *ResolveDidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registrar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDidResponse.ProtoReflect.Descriptor instead.
func (*ResolveDidResponse) Descriptor() ([]byte, []int) {
	return file_proto_files_registrar_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveDidResponse) GetResolutionError() string {
	if x != nil {
		return x.ResolutionError
	}
	return ""
}

func (x *ResolveDidResponse) GetDidDocument() string {
	if x != nil {
		return x.DidDocument
	}
	return ""
}

func (x *ResolveDidResponse) GetDidDocumentMetadata() string {
	if x != nil {
		return x.DidDocumentMetadata
	}
	return ""
}

type UpdateDidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Document      string                 `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDidRequest) Reset() {
	*x = UpdateDidRequest{}
	mi := &file_proto_files_registrar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDidRequest) ProtoMessage() {}

func (x *UpdateDidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registrar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDidRequest.ProtoReflect.Descriptor instead.
func (*UpdateDidRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_registrar_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDidRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *UpdateDidRequest) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

type UpdateDidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDidResponse) Reset() {
	*x = UpdateDidResponse{}
	mi := &file_proto_files_registrar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDidResponse) ProtoMessage() {}

func (x *UpdateDidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registrar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDidResponse.ProtoReflect.Descriptor instead.
func (*UpdateDidResponse) Descriptor() ([]byte, []int) {
	return file_proto_files_registrar_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDidResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_proto_files_registrar_proto protoreflect.FileDescriptor

const file_proto_files_registrar_proto_rawDesc = "" +
	"\n" +
	"\x1bproto-files/registrar.proto\x12\tregistrar\"V\n" +
	"\x10CreateDidRequest\x12*\n" +
	"\x11public_key_base58\x18\x01 \x01(\tR\x0fpublicKeyBase58\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\"%\n" +
	"\x11CreateDidResponse\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\"B\n" +
	"\x12RegisterDidRequest\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x12\x1a\n" +
	"\bdocument\x18\x02 \x01(\tR\bdocument\"-\n" +
	"\x13RegisterDidResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"%\n" +
	"\x11ResolveDidRequest\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\"\x96\x01\n" +
	"\x12ResolveDidResponse\x12)\n" +
	"\x10resolution_error\x18\x01 \x01(\tR\x0fresolutionError\x12!\n" +
	"\fdid_document\x18\x02 \x01(\tR\vdidDocument\x122\n" +
	"\x15did_document_metadata\x18\x03 \x01(\tR\x13didDocumentMetadata\"@\n" +
	"\x10UpdateDidRequest\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x12\x1a\n" +
	"\bdocument\x18\x02 \x01(\tR\bdocument\"+\n" +
	"\x11UpdateDidResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2\xbc\x02\n" +
	"\tRegistrar\x12H\n" +
	"\tCreateDid\x12\x1b.registrar.CreateDidRequest\x1a\x1c.registrar.CreateDidResponse\"\x00\x12N\n" +
	"\vRegisterDid\x12\x1d.registrar.RegisterDidRequest\x1a\x1e.registrar.RegisterDidResponse\"\x00\x12K\n" +
	"\n" +
	"ResolveDid\x12\x1c.registrar.ResolveDidRequest\x1a\x1d.registrar.ResolveDidResponse\"\x00\x12H\n" +
	"\tUpdateDid\x12\x1b.registrar.UpdateDidRequest\x1a\x1c.registrar.UpdateDidResponse\"\x00BH\n" +
	"\x1cio.grpc.examples.proto-filesB\x0fHelloWorldProtoP\x01Z\x15byd50-ssi/proto-filesb\x06proto3"

var (
	file_proto_files_registrar_proto_rawDescOnce sync.Once
	file_proto_files_registrar_proto_rawDescData []byte
)

func file_proto_files_registrar_proto_rawDescGZIP() []byte {
	file_proto_files_registrar_proto_rawDescOnce.Do(func() {
		file_proto_files_registrar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_files_registrar_proto_rawDesc), len(file_proto_files_registrar_proto_rawDesc)))
	})
	return file_proto_files_registrar_proto_rawDescData
}

var file_proto_files_registrar_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_files_registrar_proto_goTypes = []any{
	(*CreateDidRequest)(nil),    // 0: registrar.CreateDidRequest
	(*CreateDidResponse)(nil),   // 1: registrar.CreateDidResponse
	(*RegisterDidRequest)(nil),  // 2: registrar.RegisterDidRequest
	(*RegisterDidResponse)(nil), // 3: registrar.RegisterDidResponse
	(*ResolveDidRequest)(nil),   // 4: registrar.ResolveDidRequest
	(*ResolveDidResponse)(nil),  // 5: registrar.ResolveDidResponse
	(*UpdateDidRequest)(nil),    // 6: registrar.UpdateDidRequest
	(*UpdateDidResponse)(nil),   // 7: registrar.UpdateDidResponse
}
var file_proto_files_registrar_proto_depIdxs = []int32{
	0, // 0: registrar.Registrar.CreateDid:input_type -> registrar.CreateDidRequest
	2, // 1: registrar.Registrar.RegisterDid:input_type -> registrar.RegisterDidRequest
	4, // 2: registrar.Registrar.ResolveDid:input_type -> registrar.ResolveDidRequest
	6, // 3: registrar.Registrar.UpdateDid:input_type -> registrar.UpdateDidRequest
	1, // 4: registrar.Registrar.CreateDid:output_type -> registrar.CreateDidResponse
	3, // 5: registrar.Registrar.RegisterDid:output_type -> registrar.RegisterDidResponse
	5, // 6: registrar.Registrar.ResolveDid:output_type -> registrar.ResolveDidResponse
	7, // 7: registrar.Registrar.UpdateDid:output_type -> registrar.UpdateDidResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_files_registrar_proto_init() }
func file_proto_files_registrar_proto_init() {
	if File_proto_files_registrar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_files_registrar_proto_rawDesc), len(file_proto_files_registrar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_files_registrar_proto_goTypes,
		DependencyIndexes: file_proto_files_registrar_proto_depIdxs,
		MessageInfos:      file_proto_files_registrar_proto_msgTypes,
	}.Build()
	File_proto_files_registrar_proto = out.File
	file_proto_files_registrar_proto_goTypes = nil
	file_proto_files_registrar_proto_depIdxs = nil
}
