// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto-files/registrar.proto

package proto_files

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the publicKey.
type CreateDIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKeyBase58 string `protobuf:"bytes,1,opt,name=publicKeyBase58,proto3" json:"publicKeyBase58,omitempty"`
	Method          string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
}

func (x *CreateDIDsRequest) Reset() {
	*x = CreateDIDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_registrar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDIDsRequest) ProtoMessage() {}

func (x *CreateDIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registrar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDIDsRequest.ProtoReflect.Descriptor instead.
func (*CreateDIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_registrar_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDIDsRequest) GetPublicKeyBase58() string {
	if x != nil {
		return x.PublicKeyBase58
	}
	return ""
}

func (x *CreateDIDsRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

// The response message containing the created DID.
type CreateDIDsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (x *CreateDIDsReply) Reset() {
	*x = CreateDIDsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_registrar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDIDsReply) ProtoMessage() {}

func (x *CreateDIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registrar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDIDsReply.ProtoReflect.Descriptor instead.
func (*CreateDIDsReply) Descriptor() ([]byte, []int) {
	return file_proto_files_registrar_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDIDsReply) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

// The request message containing the publicKey.
type RegisterDIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did      string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Document string `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
}

func (x *RegisterDIDsRequest) Reset() {
	*x = RegisterDIDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_registrar_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterDIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDIDsRequest) ProtoMessage() {}

func (x *RegisterDIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registrar_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDIDsRequest.ProtoReflect.Descriptor instead.
func (*RegisterDIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_registrar_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterDIDsRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *RegisterDIDsRequest) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

// The response message containing the created DID.
type RegisterDIDsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *RegisterDIDsReply) Reset() {
	*x = RegisterDIDsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_registrar_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterDIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDIDsReply) ProtoMessage() {}

func (x *RegisterDIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registrar_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDIDsReply.ProtoReflect.Descriptor instead.
func (*RegisterDIDsReply) Descriptor() ([]byte, []int) {
	return file_proto_files_registrar_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterDIDsReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// The request message containing the DID.
type ResolveDIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (x *ResolveDIDsRequest) Reset() {
	*x = ResolveDIDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_registrar_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveDIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDIDsRequest) ProtoMessage() {}

func (x *ResolveDIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registrar_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDIDsRequest.ProtoReflect.Descriptor instead.
func (*ResolveDIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_registrar_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveDIDsRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

// The response message containing the DID document.
type ResolveDIDsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResolutionError     string `protobuf:"bytes,1,opt,name=resolutionError,proto3" json:"resolutionError,omitempty"`
	DidDocument         string `protobuf:"bytes,2,opt,name=didDocument,proto3" json:"didDocument,omitempty"`
	DidDocumentMetadata string `protobuf:"bytes,3,opt,name=didDocumentMetadata,proto3" json:"didDocumentMetadata,omitempty"`
}

func (x *ResolveDIDsReply) Reset() {
	*x = ResolveDIDsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_registrar_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveDIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDIDsReply) ProtoMessage() {}

func (x *ResolveDIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registrar_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDIDsReply.ProtoReflect.Descriptor instead.
func (*ResolveDIDsReply) Descriptor() ([]byte, []int) {
	return file_proto_files_registrar_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveDIDsReply) GetResolutionError() string {
	if x != nil {
		return x.ResolutionError
	}
	return ""
}

func (x *ResolveDIDsReply) GetDidDocument() string {
	if x != nil {
		return x.DidDocument
	}
	return ""
}

func (x *ResolveDIDsReply) GetDidDocumentMetadata() string {
	if x != nil {
		return x.DidDocumentMetadata
	}
	return ""
}

// The request message containing the DID & document.
type UpdateDIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did      string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Document string `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
}

func (x *UpdateDIDsRequest) Reset() {
	*x = UpdateDIDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_registrar_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDIDsRequest) ProtoMessage() {}

func (x *UpdateDIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registrar_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDIDsRequest.ProtoReflect.Descriptor instead.
func (*UpdateDIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_registrar_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDIDsRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *UpdateDIDsRequest) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

// The response message containing the result.
type UpdateDIDsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *UpdateDIDsReply) Reset() {
	*x = UpdateDIDsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_registrar_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDIDsReply) ProtoMessage() {}

func (x *UpdateDIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registrar_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDIDsReply.ProtoReflect.Descriptor instead.
func (*UpdateDIDsReply) Descriptor() ([]byte, []int) {
	return file_proto_files_registrar_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDIDsReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_proto_files_registrar_proto protoreflect.FileDescriptor

var file_proto_files_registrar_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x22, 0x55, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a,
	0x0f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x42, 0x61, 0x73, 0x65, 0x35, 0x38,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x42, 0x61, 0x73, 0x65, 0x35, 0x38, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x22,
	0x23, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x64, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x2b, 0x0a, 0x11, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x26, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x22, 0x90,
	0x01, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x72, 0x65,
	0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x69, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x30, 0x0a, 0x13, 0x64, 0x69, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x64, 0x69,
	0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x41, 0x0a, 0x11, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x49, 0x44, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x22, 0x29, 0x0a, 0x0f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x49,
	0x44, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32,
	0xb8, 0x02, 0x0a, 0x09, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x12, 0x47, 0x0a,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x49, 0x44, 0x12, 0x1c, 0x2e, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x49, 0x44,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x49, 0x44, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0b, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x44, 0x49, 0x44, 0x12, 0x1e, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65,
	0x44, 0x49, 0x44, 0x12, 0x1d, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x2e,
	0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x2e, 0x52,
	0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x47, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x49, 0x44, 0x12, 0x1c,
	0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x2e, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x2e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44,
	0x49, 0x44, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x6a, 0x0a, 0x1c, 0x69, 0x6f,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x42, 0x0f, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x37, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2d, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_files_registrar_proto_rawDescOnce sync.Once
	file_proto_files_registrar_proto_rawDescData = file_proto_files_registrar_proto_rawDesc
)

func file_proto_files_registrar_proto_rawDescGZIP() []byte {
	file_proto_files_registrar_proto_rawDescOnce.Do(func() {
		file_proto_files_registrar_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_files_registrar_proto_rawDescData)
	})
	return file_proto_files_registrar_proto_rawDescData
}

var file_proto_files_registrar_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_files_registrar_proto_goTypes = []interface{}{
	(*CreateDIDsRequest)(nil),   // 0: registrar.CreateDIDsRequest
	(*CreateDIDsReply)(nil),     // 1: registrar.CreateDIDsReply
	(*RegisterDIDsRequest)(nil), // 2: registrar.RegisterDIDsRequest
	(*RegisterDIDsReply)(nil),   // 3: registrar.RegisterDIDsReply
	(*ResolveDIDsRequest)(nil),  // 4: registrar.ResolveDIDsRequest
	(*ResolveDIDsReply)(nil),    // 5: registrar.ResolveDIDsReply
	(*UpdateDIDsRequest)(nil),   // 6: registrar.updateDIDsRequest
	(*UpdateDIDsReply)(nil),     // 7: registrar.updateDIDsReply
}
var file_proto_files_registrar_proto_depIdxs = []int32{
	0, // 0: registrar.Registrar.createDID:input_type -> registrar.CreateDIDsRequest
	2, // 1: registrar.Registrar.registerDID:input_type -> registrar.RegisterDIDsRequest
	4, // 2: registrar.Registrar.resolveDID:input_type -> registrar.ResolveDIDsRequest
	6, // 3: registrar.Registrar.updateDID:input_type -> registrar.updateDIDsRequest
	1, // 4: registrar.Registrar.createDID:output_type -> registrar.CreateDIDsReply
	3, // 5: registrar.Registrar.registerDID:output_type -> registrar.RegisterDIDsReply
	5, // 6: registrar.Registrar.resolveDID:output_type -> registrar.ResolveDIDsReply
	7, // 7: registrar.Registrar.updateDID:output_type -> registrar.updateDIDsReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_files_registrar_proto_init() }
func file_proto_files_registrar_proto_init() {
	if File_proto_files_registrar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_files_registrar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDIDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_registrar_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDIDsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_registrar_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterDIDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_registrar_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterDIDsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_registrar_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveDIDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_registrar_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveDIDsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_registrar_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDIDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_registrar_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDIDsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_files_registrar_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_files_registrar_proto_goTypes,
		DependencyIndexes: file_proto_files_registrar_proto_depIdxs,
		MessageInfos:      file_proto_files_registrar_proto_msgTypes,
	}.Build()
	File_proto_files_registrar_proto = out.File
	file_proto_files_registrar_proto_rawDesc = nil
	file_proto_files_registrar_proto_goTypes = nil
	file_proto_files_registrar_proto_depIdxs = nil
}
