// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto-files/registry.proto

package proto_files

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistryCreateDidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryCreateDidRequest) Reset() {
	*x = RegistryCreateDidRequest{}
	mi := &file_proto_files_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryCreateDidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryCreateDidRequest) ProtoMessage() {}

func (x *RegistryCreateDidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryCreateDidRequest.ProtoReflect.Descriptor instead.
func (*RegistryCreateDidRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_registry_proto_rawDescGZIP(), []int{0}
}

func (x *RegistryCreateDidRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type RegistryCreateDidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryCreateDidResponse) Reset() {
	*x = RegistryCreateDidResponse{}
	mi := &file_proto_files_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryCreateDidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryCreateDidResponse) ProtoMessage() {}

func (x *RegistryCreateDidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryCreateDidResponse.ProtoReflect.Descriptor instead.
func (*RegistryCreateDidResponse) Descriptor() ([]byte, []int) {
	return file_proto_files_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegistryCreateDidResponse) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type RegistryRegisterDidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Document      string                 `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryRegisterDidRequest) Reset() {
	*x = RegistryRegisterDidRequest{}
	mi := &file_proto_files_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryRegisterDidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryRegisterDidRequest) ProtoMessage() {}

func (x *RegistryRegisterDidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryRegisterDidRequest.ProtoReflect.Descriptor instead.
func (*RegistryRegisterDidRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_registry_proto_rawDescGZIP(), []int{2}
}

func (x *RegistryRegisterDidRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *RegistryRegisterDidRequest) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

type RegistryRegisterDidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryRegisterDidResponse) Reset() {
	*x = RegistryRegisterDidResponse{}
	mi := &file_proto_files_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryRegisterDidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryRegisterDidResponse) ProtoMessage() {}

func (x *RegistryRegisterDidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryRegisterDidResponse.ProtoReflect.Descriptor instead.
func (*RegistryRegisterDidResponse) Descriptor() ([]byte, []int) {
	return file_proto_files_registry_proto_rawDescGZIP(), []int{3}
}

func (x *RegistryRegisterDidResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type RegistryResolveDidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryResolveDidRequest) Reset() {
	*x = RegistryResolveDidRequest{}
	mi := &file_proto_files_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryResolveDidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryResolveDidRequest) ProtoMessage() {}

func (x *RegistryResolveDidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryResolveDidRequest.ProtoReflect.Descriptor instead.
func (*RegistryResolveDidRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_registry_proto_rawDescGZIP(), []int{4}
}

func (x *RegistryResolveDidRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type RegistryResolveDidResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ResolutionError     string                 `protobuf:"bytes,1,opt,name=resolution_error,json=resolutionError,proto3" json:"resolution_error,omitempty"`
	DidDocument         string                 `protobuf:"bytes,2,opt,name=did_document,json=didDocument,proto3" json:"did_document,omitempty"`
	DidDocumentMetadata string                 `protobuf:"bytes,3,opt,name=did_document_metadata,json=didDocumentMetadata,proto3" json:"did_document_metadata,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegistryResolveDidResponse) Reset() {
	*x = RegistryResolveDidResponse{}
	mi := &file_proto_files_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryResolveDidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryResolveDidResponse) ProtoMessage() {}

func (x *RegistryResolveDidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryResolveDidResponse.ProtoReflect.Descriptor instead.
func (*RegistryResolveDidResponse) Descriptor() ([]byte, []int) {
	return file_proto_files_registry_proto_rawDescGZIP(), []int{5}
}

func (x *RegistryResolveDidResponse) GetResolutionError() string {
	if x != nil {
		return x.ResolutionError
	}
	return ""
}

func (x *RegistryResolveDidResponse) GetDidDocument() string {
	if x != nil {
		return x.DidDocument
	}
	return ""
}

func (x *RegistryResolveDidResponse) GetDidDocumentMetadata() string {
	if x != nil {
		return x.DidDocumentMetadata
	}
	return ""
}

type RegistryUpdateDidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Document      string                 `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryUpdateDidRequest) Reset() {
	*x = RegistryUpdateDidRequest{}
	mi := &file_proto_files_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryUpdateDidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryUpdateDidRequest) ProtoMessage() {}

func (x *RegistryUpdateDidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryUpdateDidRequest.ProtoReflect.Descriptor instead.
func (*RegistryUpdateDidRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_registry_proto_rawDescGZIP(), []int{6}
}

func (x *RegistryUpdateDidRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *RegistryUpdateDidRequest) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

type RegistryUpdateDidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryUpdateDidResponse) Reset() {
	*x = RegistryUpdateDidResponse{}
	mi := &file_proto_files_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryUpdateDidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryUpdateDidResponse) ProtoMessage() {}

func (x *RegistryUpdateDidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryUpdateDidResponse.ProtoReflect.Descriptor instead.
func (*RegistryUpdateDidResponse) Descriptor() ([]byte, []int) {
	return file_proto_files_registry_proto_rawDescGZIP(), []int{7}
}

func (x *RegistryUpdateDidResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_proto_files_registry_proto protoreflect.FileDescriptor

const file_proto_files_registry_proto_rawDesc = "" +
	"\n" +
	"\x1aproto-files/registry.proto\x12\bregistry\"9\n" +
	"\x18RegistryCreateDidRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\"-\n" +
	"\x19RegistryCreateDidResponse\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\"J\n" +
	"\x1aRegistryRegisterDidRequest\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x12\x1a\n" +
	"\bdocument\x18\x02 \x01(\tR\bdocument\"5\n" +
	"\x1bRegistryRegisterDidResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"-\n" +
	"\x19RegistryResolveDidRequest\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\"\x9e\x01\n" +
	"\x1aRegistryResolveDidResponse\x12)\n" +
	"\x10resolution_error\x18\x01 \x01(\tR\x0fresolutionError\x12!\n" +
	"\fdid_document\x18\x02 \x01(\tR\vdidDocument\x122\n" +
	"\x15did_document_metadata\x18\x03 \x01(\tR\x13didDocumentMetadata\"H\n" +
	"\x18RegistryUpdateDidRequest\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x12\x1a\n" +
	"\bdocument\x18\x02 \x01(\tR\bdocument\"3\n" +
	"\x19RegistryUpdateDidResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2\x95\x02\n" +
	"\bRegistry\x12V\n" +
	"\tCreateDid\x12\".registry.RegistryCreateDidRequest\x1a#.registry.RegistryCreateDidResponse\"\x00\x12Y\n" +
	"\n" +
	"ResolveDid\x12#.registry.RegistryResolveDidRequest\x1a$.registry.RegistryResolveDidResponse\"\x00\x12V\n" +
	"\tUpdateDid\x12\".registry.RegistryUpdateDidRequest\x1a#.registry.RegistryUpdateDidResponse\"\x00BH\n" +
	"\x1cio.grpc.examples.proto-filesB\x0fHelloWorldProtoP\x01Z\x15byd50-ssi/proto-filesb\x06proto3"

var (
	file_proto_files_registry_proto_rawDescOnce sync.Once
	file_proto_files_registry_proto_rawDescData []byte
)

func file_proto_files_registry_proto_rawDescGZIP() []byte {
	file_proto_files_registry_proto_rawDescOnce.Do(func() {
		file_proto_files_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_files_registry_proto_rawDesc), len(file_proto_files_registry_proto_rawDesc)))
	})
	return file_proto_files_registry_proto_rawDescData
}

var file_proto_files_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_files_registry_proto_goTypes = []any{
	(*RegistryCreateDidRequest)(nil),    // 0: registry.RegistryCreateDidRequest
	(*RegistryCreateDidResponse)(nil),   // 1: registry.RegistryCreateDidResponse
	(*RegistryRegisterDidRequest)(nil),  // 2: registry.RegistryRegisterDidRequest
	(*RegistryRegisterDidResponse)(nil), // 3: registry.RegistryRegisterDidResponse
	(*RegistryResolveDidRequest)(nil),   // 4: registry.RegistryResolveDidRequest
	(*RegistryResolveDidResponse)(nil),  // 5: registry.RegistryResolveDidResponse
	(*RegistryUpdateDidRequest)(nil),    // 6: registry.RegistryUpdateDidRequest
	(*RegistryUpdateDidResponse)(nil),   // 7: registry.RegistryUpdateDidResponse
}
var file_proto_files_registry_proto_depIdxs = []int32{
	0, // 0: registry.Registry.CreateDid:input_type -> registry.RegistryCreateDidRequest
	4, // 1: registry.Registry.ResolveDid:input_type -> registry.RegistryResolveDidRequest
	6, // 2: registry.Registry.UpdateDid:input_type -> registry.RegistryUpdateDidRequest
	1, // 3: registry.Registry.CreateDid:output_type -> registry.RegistryCreateDidResponse
	5, // 4: registry.Registry.ResolveDid:output_type -> registry.RegistryResolveDidResponse
	7, // 5: registry.Registry.UpdateDid:output_type -> registry.RegistryUpdateDidResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_files_registry_proto_init() }
func file_proto_files_registry_proto_init() {
	if File_proto_files_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_files_registry_proto_rawDesc), len(file_proto_files_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_files_registry_proto_goTypes,
		DependencyIndexes: file_proto_files_registry_proto_depIdxs,
		MessageInfos:      file_proto_files_registry_proto_msgTypes,
	}.Build()
	File_proto_files_registry_proto = out.File
	file_proto_files_registry_proto_goTypes = nil
	file_proto_files_registry_proto_depIdxs = nil
}
