// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto-files/relyingparty.proto

package proto_files

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeRequest) Reset() {
	*x = ChallengeRequest{}
	mi := &file_proto_files_relyingparty_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeRequest) ProtoMessage() {}

func (x *ChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_relyingparty_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeRequest.ProtoReflect.Descriptor instead.
func (*ChallengeRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_relyingparty_proto_rawDescGZIP(), []int{0}
}

func (x *ChallengeRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type ChallengeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthChallenge string                 `protobuf:"bytes,1,opt,name=auth_challenge,json=authChallenge,proto3" json:"auth_challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeReply) Reset() {
	*x = ChallengeReply{}
	mi := &file_proto_files_relyingparty_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeReply) ProtoMessage() {}

func (x *ChallengeReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_relyingparty_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeReply.ProtoReflect.Descriptor instead.
func (*ChallengeReply) Descriptor() ([]byte, []int) {
	return file_proto_files_relyingparty_proto_rawDescGZIP(), []int{1}
}

func (x *ChallengeReply) GetAuthChallenge() string {
	if x != nil {
		return x.AuthChallenge
	}
	return ""
}

type ResponseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthResponse  string                 `protobuf:"bytes,1,opt,name=auth_response,json=authResponse,proto3" json:"auth_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseRequest) Reset() {
	*x = ResponseRequest{}
	mi := &file_proto_files_relyingparty_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRequest) ProtoMessage() {}

func (x *ResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_relyingparty_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRequest.ProtoReflect.Descriptor instead.
func (*ResponseRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_relyingparty_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseRequest) GetAuthResponse() string {
	if x != nil {
		return x.AuthResponse
	}
	return ""
}

type ResponseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseReply) Reset() {
	*x = ResponseReply{}
	mi := &file_proto_files_relyingparty_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseReply) ProtoMessage() {}

func (x *ResponseReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_relyingparty_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseReply.ProtoReflect.Descriptor instead.
func (*ResponseReply) Descriptor() ([]byte, []int) {
	return file_proto_files_relyingparty_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SimplePresentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SimplePresent string                 `protobuf:"bytes,1,opt,name=simple_present,json=simplePresent,proto3" json:"simple_present,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimplePresentRequest) Reset() {
	*x = SimplePresentRequest{}
	mi := &file_proto_files_relyingparty_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimplePresentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimplePresentRequest) ProtoMessage() {}

func (x *SimplePresentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_relyingparty_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimplePresentRequest.ProtoReflect.Descriptor instead.
func (*SimplePresentRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_relyingparty_proto_rawDescGZIP(), []int{4}
}

func (x *SimplePresentRequest) GetSimplePresent() string {
	if x != nil {
		return x.SimplePresent
	}
	return ""
}

type SimplePresentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimplePresentReply) Reset() {
	*x = SimplePresentReply{}
	mi := &file_proto_files_relyingparty_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimplePresentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimplePresentReply) ProtoMessage() {}

func (x *SimplePresentReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_relyingparty_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimplePresentReply.ProtoReflect.Descriptor instead.
func (*SimplePresentReply) Descriptor() ([]byte, []int) {
	return file_proto_files_relyingparty_proto_rawDescGZIP(), []int{5}
}

func (x *SimplePresentReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type VerifyVpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vp            string                 `protobuf:"bytes,1,opt,name=vp,proto3" json:"vp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyVpRequest) Reset() {
	*x = VerifyVpRequest{}
	mi := &file_proto_files_relyingparty_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyVpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyVpRequest) ProtoMessage() {}

func (x *VerifyVpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_relyingparty_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyVpRequest.ProtoReflect.Descriptor instead.
func (*VerifyVpRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_relyingparty_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyVpRequest) GetVp() string {
	if x != nil {
		return x.Vp
	}
	return ""
}

type VerifyVpReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyVpReply) Reset() {
	*x = VerifyVpReply{}
	mi := &file_proto_files_relyingparty_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyVpReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyVpReply) ProtoMessage() {}

func (x *VerifyVpReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_relyingparty_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyVpReply.ProtoReflect.Descriptor instead.
func (*VerifyVpReply) Descriptor() ([]byte, []int) {
	return file_proto_files_relyingparty_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyVpReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_proto_files_relyingparty_proto protoreflect.FileDescriptor

const file_proto_files_relyingparty_proto_rawDesc = "" +
	"\n" +
	"\x1eproto-files/relyingparty.proto\x12\frelyingparty\"$\n" +
	"\x10ChallengeRequest\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\"7\n" +
	"\x0eChallengeReply\x12%\n" +
	"\x0eauth_challenge\x18\x01 \x01(\tR\rauthChallenge\"6\n" +
	"\x0fResponseRequest\x12#\n" +
	"\rauth_response\x18\x01 \x01(\tR\fauthResponse\")\n" +
	"\rResponseReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"=\n" +
	"\x14SimplePresentRequest\x12%\n" +
	"\x0esimple_present\x18\x01 \x01(\tR\rsimplePresent\",\n" +
	"\x12SimplePresentReply\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"!\n" +
	"\x0fVerifyVpRequest\x12\x0e\n" +
	"\x02vp\x18\x01 \x01(\tR\x02vp\"'\n" +
	"\rVerifyVpReply\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2\xd0\x02\n" +
	"\fRelyingParty\x12O\n" +
	"\rAuthChallenge\x12\x1e.relyingparty.ChallengeRequest\x1a\x1c.relyingparty.ChallengeReply\"\x00\x12L\n" +
	"\fAuthResponse\x12\x1d.relyingparty.ResponseRequest\x1a\x1b.relyingparty.ResponseReply\"\x00\x12W\n" +
	"\rSimplePresent\x12\".relyingparty.SimplePresentRequest\x1a .relyingparty.SimplePresentReply\"\x00\x12H\n" +
	"\bVerifyVp\x12\x1d.relyingparty.VerifyVpRequest\x1a\x1b.relyingparty.VerifyVpReply\"\x00BH\n" +
	"\x1cio.grpc.examples.proto-filesB\x0fHelloWorldProtoP\x01Z\x15byd50-ssi/proto-filesb\x06proto3"

var (
	file_proto_files_relyingparty_proto_rawDescOnce sync.Once
	file_proto_files_relyingparty_proto_rawDescData []byte
)

func file_proto_files_relyingparty_proto_rawDescGZIP() []byte {
	file_proto_files_relyingparty_proto_rawDescOnce.Do(func() {
		file_proto_files_relyingparty_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_files_relyingparty_proto_rawDesc), len(file_proto_files_relyingparty_proto_rawDesc)))
	})
	return file_proto_files_relyingparty_proto_rawDescData
}

var file_proto_files_relyingparty_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_files_relyingparty_proto_goTypes = []any{
	(*ChallengeRequest)(nil),     // 0: relyingparty.ChallengeRequest
	(*ChallengeReply)(nil),       // 1: relyingparty.ChallengeReply
	(*ResponseRequest)(nil),      // 2: relyingparty.ResponseRequest
	(*ResponseReply)(nil),        // 3: relyingparty.ResponseReply
	(*SimplePresentRequest)(nil), // 4: relyingparty.SimplePresentRequest
	(*SimplePresentReply)(nil),   // 5: relyingparty.SimplePresentReply
	(*VerifyVpRequest)(nil),      // 6: relyingparty.VerifyVpRequest
	(*VerifyVpReply)(nil),        // 7: relyingparty.VerifyVpReply
}
var file_proto_files_relyingparty_proto_depIdxs = []int32{
	0, // 0: relyingparty.RelyingParty.AuthChallenge:input_type -> relyingparty.ChallengeRequest
	2, // 1: relyingparty.RelyingParty.AuthResponse:input_type -> relyingparty.ResponseRequest
	4, // 2: relyingparty.RelyingParty.SimplePresent:input_type -> relyingparty.SimplePresentRequest
	6, // 3: relyingparty.RelyingParty.VerifyVp:input_type -> relyingparty.VerifyVpRequest
	1, // 4: relyingparty.RelyingParty.AuthChallenge:output_type -> relyingparty.ChallengeReply
	3, // 5: relyingparty.RelyingParty.AuthResponse:output_type -> relyingparty.ResponseReply
	5, // 6: relyingparty.RelyingParty.SimplePresent:output_type -> relyingparty.SimplePresentReply
	7, // 7: relyingparty.RelyingParty.VerifyVp:output_type -> relyingparty.VerifyVpReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_files_relyingparty_proto_init() }
func file_proto_files_relyingparty_proto_init() {
	if File_proto_files_relyingparty_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_files_relyingparty_proto_rawDesc), len(file_proto_files_relyingparty_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_files_relyingparty_proto_goTypes,
		DependencyIndexes: file_proto_files_relyingparty_proto_depIdxs,
		MessageInfos:      file_proto_files_relyingparty_proto_msgTypes,
	}.Build()
	File_proto_files_relyingparty_proto = out.File
	file_proto_files_relyingparty_proto_goTypes = nil
	file_proto_files_relyingparty_proto_depIdxs = nil
}
