// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto-files/relyingparty.proto

package proto_files

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RelyingPartyClient is the client API for RelyingParty service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RelyingPartyClient interface {
	// Sends a greeting
	AuthChallenge(ctx context.Context, in *ChallengeRequest, opts ...grpc.CallOption) (*ChallengeReply, error)
	AuthResponse(ctx context.Context, in *ResponseRequest, opts ...grpc.CallOption) (*ResponseReply, error)
	SimplePresent(ctx context.Context, in *SimplePresentRequest, opts ...grpc.CallOption) (*SimplePresentReply, error)
	VerifyVp(ctx context.Context, in *VerifyVpRequest, opts ...grpc.CallOption) (*VerifyVpReply, error)
}

type relyingPartyClient struct {
	cc grpc.ClientConnInterface
}

func NewRelyingPartyClient(cc grpc.ClientConnInterface) RelyingPartyClient {
	return &relyingPartyClient{cc}
}

func (c *relyingPartyClient) AuthChallenge(ctx context.Context, in *ChallengeRequest, opts ...grpc.CallOption) (*ChallengeReply, error) {
	out := new(ChallengeReply)
	err := c.cc.Invoke(ctx, "/relyingparty.RelyingParty/AuthChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relyingPartyClient) AuthResponse(ctx context.Context, in *ResponseRequest, opts ...grpc.CallOption) (*ResponseReply, error) {
	out := new(ResponseReply)
	err := c.cc.Invoke(ctx, "/relyingparty.RelyingParty/AuthResponse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relyingPartyClient) SimplePresent(ctx context.Context, in *SimplePresentRequest, opts ...grpc.CallOption) (*SimplePresentReply, error) {
	out := new(SimplePresentReply)
	err := c.cc.Invoke(ctx, "/relyingparty.RelyingParty/SimplePresent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relyingPartyClient) VerifyVp(ctx context.Context, in *VerifyVpRequest, opts ...grpc.CallOption) (*VerifyVpReply, error) {
	out := new(VerifyVpReply)
	err := c.cc.Invoke(ctx, "/relyingparty.RelyingParty/VerifyVp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelyingPartyServer is the server API for RelyingParty service.
// All implementations must embed UnimplementedRelyingPartyServer
// for forward compatibility
type RelyingPartyServer interface {
	// Sends a greeting
	AuthChallenge(context.Context, *ChallengeRequest) (*ChallengeReply, error)
	AuthResponse(context.Context, *ResponseRequest) (*ResponseReply, error)
	SimplePresent(context.Context, *SimplePresentRequest) (*SimplePresentReply, error)
	VerifyVp(context.Context, *VerifyVpRequest) (*VerifyVpReply, error)
	mustEmbedUnimplementedRelyingPartyServer()
}

// UnimplementedRelyingPartyServer must be embedded to have forward compatible implementations.
type UnimplementedRelyingPartyServer struct {
}

func (UnimplementedRelyingPartyServer) AuthChallenge(context.Context, *ChallengeRequest) (*ChallengeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthChallenge not implemented")
}
func (UnimplementedRelyingPartyServer) AuthResponse(context.Context, *ResponseRequest) (*ResponseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthResponse not implemented")
}
func (UnimplementedRelyingPartyServer) SimplePresent(context.Context, *SimplePresentRequest) (*SimplePresentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimplePresent not implemented")
}
func (UnimplementedRelyingPartyServer) VerifyVp(context.Context, *VerifyVpRequest) (*VerifyVpReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyVp not implemented")
}
func (UnimplementedRelyingPartyServer) mustEmbedUnimplementedRelyingPartyServer() {}

// UnsafeRelyingPartyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelyingPartyServer will
// result in compilation errors.
type UnsafeRelyingPartyServer interface {
	mustEmbedUnimplementedRelyingPartyServer()
}

func RegisterRelyingPartyServer(s grpc.ServiceRegistrar, srv RelyingPartyServer) {
	s.RegisterService(&RelyingParty_ServiceDesc, srv)
}

func _RelyingParty_AuthChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelyingPartyServer).AuthChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relyingparty.RelyingParty/AuthChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelyingPartyServer).AuthChallenge(ctx, req.(*ChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelyingParty_AuthResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelyingPartyServer).AuthResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relyingparty.RelyingParty/AuthResponse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelyingPartyServer).AuthResponse(ctx, req.(*ResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelyingParty_SimplePresent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimplePresentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelyingPartyServer).SimplePresent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relyingparty.RelyingParty/SimplePresent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelyingPartyServer).SimplePresent(ctx, req.(*SimplePresentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelyingParty_VerifyVp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyVpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelyingPartyServer).VerifyVp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relyingparty.RelyingParty/VerifyVp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelyingPartyServer).VerifyVp(ctx, req.(*VerifyVpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RelyingParty_ServiceDesc is the grpc.ServiceDesc for RelyingParty service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelyingParty_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "relyingparty.RelyingParty",
	HandlerType: (*RelyingPartyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthChallenge",
			Handler:    _RelyingParty_AuthChallenge_Handler,
		},
		{
			MethodName: "AuthResponse",
			Handler:    _RelyingParty_AuthResponse_Handler,
		},
		{
			MethodName: "SimplePresent",
			Handler:    _RelyingParty_SimplePresent_Handler,
		},
		{
			MethodName: "VerifyVp",
			Handler:    _RelyingParty_VerifyVp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto-files/relyingparty.proto",
}
