// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto-files/relyingparty.proto

package proto_files

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's DID.
type ChallengeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (x *ChallengeRequest) Reset() {
	*x = ChallengeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_relyingparty_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeRequest) ProtoMessage() {}

func (x *ChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_relyingparty_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeRequest.ProtoReflect.Descriptor instead.
func (*ChallengeRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_relyingparty_proto_rawDescGZIP(), []int{0}
}

func (x *ChallengeRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

// The response message containing the Auth-challenge Strings
type ChallengeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthChallenge string `protobuf:"bytes,1,opt,name=authChallenge,proto3" json:"authChallenge,omitempty"`
}

func (x *ChallengeReply) Reset() {
	*x = ChallengeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_relyingparty_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChallengeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeReply) ProtoMessage() {}

func (x *ChallengeReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_relyingparty_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeReply.ProtoReflect.Descriptor instead.
func (*ChallengeReply) Descriptor() ([]byte, []int) {
	return file_proto_files_relyingparty_proto_rawDescGZIP(), []int{1}
}

func (x *ChallengeReply) GetAuthChallenge() string {
	if x != nil {
		return x.AuthChallenge
	}
	return ""
}

// The request message containing the user's DID.
type ResponseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthResponse string `protobuf:"bytes,1,opt,name=authResponse,proto3" json:"authResponse,omitempty"`
}

func (x *ResponseRequest) Reset() {
	*x = ResponseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_relyingparty_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRequest) ProtoMessage() {}

func (x *ResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_relyingparty_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRequest.ProtoReflect.Descriptor instead.
func (*ResponseRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_relyingparty_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseRequest) GetAuthResponse() string {
	if x != nil {
		return x.AuthResponse
	}
	return ""
}

// The response message containing the Auth-challenge Strings
type ResponseReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ResponseReply) Reset() {
	*x = ResponseReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_relyingparty_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseReply) ProtoMessage() {}

func (x *ResponseReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_relyingparty_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseReply.ProtoReflect.Descriptor instead.
func (*ResponseReply) Descriptor() ([]byte, []int) {
	return file_proto_files_relyingparty_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The request message containing the simplePresent.
type SimplePresentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SimplePresent string `protobuf:"bytes,1,opt,name=simplePresent,proto3" json:"simplePresent,omitempty"`
}

func (x *SimplePresentRequest) Reset() {
	*x = SimplePresentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_relyingparty_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimplePresentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimplePresentRequest) ProtoMessage() {}

func (x *SimplePresentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_relyingparty_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimplePresentRequest.ProtoReflect.Descriptor instead.
func (*SimplePresentRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_relyingparty_proto_rawDescGZIP(), []int{4}
}

func (x *SimplePresentRequest) GetSimplePresent() string {
	if x != nil {
		return x.SimplePresent
	}
	return ""
}

// The response message containing the result
type SimplePresentReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SimplePresentReply) Reset() {
	*x = SimplePresentReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_relyingparty_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimplePresentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimplePresentReply) ProtoMessage() {}

func (x *SimplePresentReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_relyingparty_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimplePresentReply.ProtoReflect.Descriptor instead.
func (*SimplePresentReply) Descriptor() ([]byte, []int) {
	return file_proto_files_relyingparty_proto_rawDescGZIP(), []int{5}
}

func (x *SimplePresentReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// The request message containing the simplePresent.
type VerifyVpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vp string `protobuf:"bytes,1,opt,name=vp,proto3" json:"vp,omitempty"`
}

func (x *VerifyVpRequest) Reset() {
	*x = VerifyVpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_relyingparty_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyVpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyVpRequest) ProtoMessage() {}

func (x *VerifyVpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_relyingparty_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyVpRequest.ProtoReflect.Descriptor instead.
func (*VerifyVpRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_relyingparty_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyVpRequest) GetVp() string {
	if x != nil {
		return x.Vp
	}
	return ""
}

// The response message containing the result
type VerifyVpReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *VerifyVpReply) Reset() {
	*x = VerifyVpReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_relyingparty_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyVpReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyVpReply) ProtoMessage() {}

func (x *VerifyVpReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_relyingparty_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyVpReply.ProtoReflect.Descriptor instead.
func (*VerifyVpReply) Descriptor() ([]byte, []int) {
	return file_proto_files_relyingparty_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyVpReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_proto_files_relyingparty_proto protoreflect.FileDescriptor

var file_proto_files_relyingparty_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x72, 0x65,
	0x6c, 0x79, 0x69, 0x6e, 0x67, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x72, 0x65, 0x6c, 0x79, 0x69, 0x6e, 0x67, 0x70, 0x61, 0x72, 0x74, 0x79, 0x22, 0x24,
	0x0a, 0x10, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x64, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x43, 0x68,
	0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61,
	0x75, 0x74, 0x68, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x22, 0x35, 0x0a, 0x0f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x22, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x29, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3c,
	0x0a, 0x14, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65,
	0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73,
	0x69, 0x6d, 0x70, 0x6c, 0x65, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x22, 0x2c, 0x0a, 0x12,
	0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x21, 0x0a, 0x0f, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x56, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x76, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x76, 0x70, 0x22, 0x27, 0x0a,
	0x0d, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x56, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xd0, 0x02, 0x0a, 0x0c, 0x52, 0x65, 0x6c, 0x79, 0x69,
	0x6e, 0x67, 0x50, 0x61, 0x72, 0x74, 0x79, 0x12, 0x4f, 0x0a, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x43,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12, 0x1e, 0x2e, 0x72, 0x65, 0x6c, 0x79, 0x69,
	0x6e, 0x67, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x72, 0x65, 0x6c, 0x79, 0x69,
	0x6e, 0x67, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0c, 0x41, 0x75, 0x74, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x2e, 0x72, 0x65, 0x6c, 0x79, 0x69,
	0x6e, 0x67, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x72, 0x65, 0x6c, 0x79, 0x69, 0x6e,
	0x67, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x0d, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65,
	0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x2e, 0x72, 0x65, 0x6c, 0x79, 0x69, 0x6e,
	0x67, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x50, 0x72, 0x65,
	0x73, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x72, 0x65,
	0x6c, 0x79, 0x69, 0x6e, 0x67, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c,
	0x65, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x48, 0x0a, 0x08, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x56, 0x70, 0x12, 0x1d, 0x2e, 0x72, 0x65,
	0x6c, 0x79, 0x69, 0x6e, 0x67, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x56, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x72, 0x65, 0x6c,
	0x79, 0x69, 0x6e, 0x67, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x56, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x6a, 0x0a, 0x1c, 0x69, 0x6f, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x42, 0x0f, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x57, 0x6f, 0x72, 0x6c, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x37, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_files_relyingparty_proto_rawDescOnce sync.Once
	file_proto_files_relyingparty_proto_rawDescData = file_proto_files_relyingparty_proto_rawDesc
)

func file_proto_files_relyingparty_proto_rawDescGZIP() []byte {
	file_proto_files_relyingparty_proto_rawDescOnce.Do(func() {
		file_proto_files_relyingparty_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_files_relyingparty_proto_rawDescData)
	})
	return file_proto_files_relyingparty_proto_rawDescData
}

var file_proto_files_relyingparty_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_files_relyingparty_proto_goTypes = []interface{}{
	(*ChallengeRequest)(nil),     // 0: relyingparty.ChallengeRequest
	(*ChallengeReply)(nil),       // 1: relyingparty.ChallengeReply
	(*ResponseRequest)(nil),      // 2: relyingparty.ResponseRequest
	(*ResponseReply)(nil),        // 3: relyingparty.ResponseReply
	(*SimplePresentRequest)(nil), // 4: relyingparty.SimplePresentRequest
	(*SimplePresentReply)(nil),   // 5: relyingparty.SimplePresentReply
	(*VerifyVpRequest)(nil),      // 6: relyingparty.VerifyVpRequest
	(*VerifyVpReply)(nil),        // 7: relyingparty.VerifyVpReply
}
var file_proto_files_relyingparty_proto_depIdxs = []int32{
	0, // 0: relyingparty.RelyingParty.AuthChallenge:input_type -> relyingparty.ChallengeRequest
	2, // 1: relyingparty.RelyingParty.AuthResponse:input_type -> relyingparty.ResponseRequest
	4, // 2: relyingparty.RelyingParty.SimplePresent:input_type -> relyingparty.SimplePresentRequest
	6, // 3: relyingparty.RelyingParty.VerifyVp:input_type -> relyingparty.VerifyVpRequest
	1, // 4: relyingparty.RelyingParty.AuthChallenge:output_type -> relyingparty.ChallengeReply
	3, // 5: relyingparty.RelyingParty.AuthResponse:output_type -> relyingparty.ResponseReply
	5, // 6: relyingparty.RelyingParty.SimplePresent:output_type -> relyingparty.SimplePresentReply
	7, // 7: relyingparty.RelyingParty.VerifyVp:output_type -> relyingparty.VerifyVpReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_files_relyingparty_proto_init() }
func file_proto_files_relyingparty_proto_init() {
	if File_proto_files_relyingparty_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_files_relyingparty_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChallengeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_relyingparty_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChallengeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_relyingparty_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_relyingparty_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_relyingparty_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimplePresentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_relyingparty_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimplePresentReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_relyingparty_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyVpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_relyingparty_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyVpReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_files_relyingparty_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_files_relyingparty_proto_goTypes,
		DependencyIndexes: file_proto_files_relyingparty_proto_depIdxs,
		MessageInfos:      file_proto_files_relyingparty_proto_msgTypes,
	}.Build()
	File_proto_files_relyingparty_proto = out.File
	file_proto_files_relyingparty_proto_rawDesc = nil
	file_proto_files_relyingparty_proto_goTypes = nil
	file_proto_files_relyingparty_proto_depIdxs = nil
}
